/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api;

import static com.clerk.backend_api.operations.Operations.RequestOperation;

import com.clerk.backend_api.models.operations.AssignPermissionToOrganizationRoleRequest;
import com.clerk.backend_api.models.operations.AssignPermissionToOrganizationRoleRequestBuilder;
import com.clerk.backend_api.models.operations.AssignPermissionToOrganizationRoleResponse;
import com.clerk.backend_api.models.operations.CreateOrganizationRoleRequestBody;
import com.clerk.backend_api.models.operations.CreateOrganizationRoleRequestBuilder;
import com.clerk.backend_api.models.operations.CreateOrganizationRoleResponse;
import com.clerk.backend_api.models.operations.DeleteOrganizationRoleRequest;
import com.clerk.backend_api.models.operations.DeleteOrganizationRoleRequestBuilder;
import com.clerk.backend_api.models.operations.DeleteOrganizationRoleResponse;
import com.clerk.backend_api.models.operations.GetOrganizationRoleRequest;
import com.clerk.backend_api.models.operations.GetOrganizationRoleRequestBuilder;
import com.clerk.backend_api.models.operations.GetOrganizationRoleResponse;
import com.clerk.backend_api.models.operations.ListOrganizationRolesRequest;
import com.clerk.backend_api.models.operations.ListOrganizationRolesRequestBuilder;
import com.clerk.backend_api.models.operations.ListOrganizationRolesResponse;
import com.clerk.backend_api.models.operations.RemovePermissionFromOrganizationRoleRequest;
import com.clerk.backend_api.models.operations.RemovePermissionFromOrganizationRoleRequestBuilder;
import com.clerk.backend_api.models.operations.RemovePermissionFromOrganizationRoleResponse;
import com.clerk.backend_api.models.operations.UpdateOrganizationRoleRequest;
import com.clerk.backend_api.models.operations.UpdateOrganizationRoleRequestBody;
import com.clerk.backend_api.models.operations.UpdateOrganizationRoleRequestBuilder;
import com.clerk.backend_api.models.operations.UpdateOrganizationRoleResponse;
import com.clerk.backend_api.operations.AssignPermissionToOrganizationRole;
import com.clerk.backend_api.operations.CreateOrganizationRole;
import com.clerk.backend_api.operations.DeleteOrganizationRole;
import com.clerk.backend_api.operations.GetOrganizationRole;
import com.clerk.backend_api.operations.ListOrganizationRoles;
import com.clerk.backend_api.operations.RemovePermissionFromOrganizationRole;
import com.clerk.backend_api.operations.UpdateOrganizationRole;
import com.clerk.backend_api.utils.Headers;
import com.clerk.backend_api.utils.Options;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;


public class OrganizationRoles {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;

    OrganizationRoles(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * Get a list of organization roles
     * 
     * <p>This request returns the list of organization roles for the instance.
     * Results can be paginated using the optional `limit` and `offset` query parameters.
     * The organization roles are ordered by descending creation date.
     * Most recent roles will be returned first.
     * 
     * @return The call builder
     */
    public ListOrganizationRolesRequestBuilder list() {
        return new ListOrganizationRolesRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a list of organization roles
     * 
     * <p>This request returns the list of organization roles for the instance.
     * Results can be paginated using the optional `limit` and `offset` query parameters.
     * The organization roles are ordered by descending creation date.
     * Most recent roles will be returned first.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListOrganizationRolesResponse listDirect() {
        return list(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * Get a list of organization roles
     * 
     * <p>This request returns the list of organization roles for the instance.
     * Results can be paginated using the optional `limit` and `offset` query parameters.
     * The organization roles are ordered by descending creation date.
     * Most recent roles will be returned first.
     * 
     * @param query Returns organization roles with ID, name, or key that match the given query.
     *         Uses exact match for organization role ID and partial match for name and key.
     * @param orderBy Allows to return organization roles in a particular order.
     *         At the moment, you can order the returned organization roles by their `created_at`, `name`, or `key`.
     *         In order to specify the direction, you can use the `+/-` symbols prepended in the property to order by.
     *         For example, if you want organization roles to be returned in descending order according to their `created_at` property, you can use `-created_at`.
     *         If you don't use `+` or `-`, then `+` is implied.
     *         Defaults to `-created_at`.
     * @param limit Applies a limit to the number of results returned.
     *         Can be used for paginating the results together with `offset`.
     * @param offset Skip the first `offset` results when paginating.
     *         Needs to be an integer greater or equal to zero.
     *         To be used in conjunction with `limit`.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListOrganizationRolesResponse list(
            Optional<String> query, Optional<String> orderBy,
            Optional<Long> limit, Optional<Long> offset,
            Optional<Options> options) {
        ListOrganizationRolesRequest request =
            ListOrganizationRolesRequest
                .builder()
                .query(query)
                .orderBy(orderBy)
                .limit(limit)
                .offset(offset)
                .build();
        RequestOperation<ListOrganizationRolesRequest, ListOrganizationRolesResponse> operation
              = new ListOrganizationRoles.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create an organization role
     * 
     * <p>Creates a new organization role with the given name and permissions for an instance.
     * The key must be unique for the instance and start with the 'org:' prefix, followed by lowercase
     * alphanumeric characters and underscores only.
     * You can optionally provide a description for the role and specify whether it should be included in
     * the initial role set.
     * Organization roles support permissions that can be assigned to control access within the
     * organization.
     * 
     * @return The call builder
     */
    public CreateOrganizationRoleRequestBuilder create() {
        return new CreateOrganizationRoleRequestBuilder(sdkConfiguration);
    }

    /**
     * Create an organization role
     * 
     * <p>Creates a new organization role with the given name and permissions for an instance.
     * The key must be unique for the instance and start with the 'org:' prefix, followed by lowercase
     * alphanumeric characters and underscores only.
     * You can optionally provide a description for the role and specify whether it should be included in
     * the initial role set.
     * Organization roles support permissions that can be assigned to control access within the
     * organization.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateOrganizationRoleResponse create(CreateOrganizationRoleRequestBody request) {
        return create(request, Optional.empty());
    }

    /**
     * Create an organization role
     * 
     * <p>Creates a new organization role with the given name and permissions for an instance.
     * The key must be unique for the instance and start with the 'org:' prefix, followed by lowercase
     * alphanumeric characters and underscores only.
     * You can optionally provide a description for the role and specify whether it should be included in
     * the initial role set.
     * Organization roles support permissions that can be assigned to control access within the
     * organization.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateOrganizationRoleResponse create(CreateOrganizationRoleRequestBody request, Optional<Options> options) {
        RequestOperation<CreateOrganizationRoleRequestBody, CreateOrganizationRoleResponse> operation
              = new CreateOrganizationRole.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve an organization role
     * 
     * <p>Use this request to retrieve an existing organization role by its ID.
     * 
     * @return The call builder
     */
    public GetOrganizationRoleRequestBuilder get() {
        return new GetOrganizationRoleRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve an organization role
     * 
     * <p>Use this request to retrieve an existing organization role by its ID.
     * 
     * @param organizationRoleId The ID of the organization role
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetOrganizationRoleResponse get(String organizationRoleId) {
        return get(organizationRoleId, Optional.empty());
    }

    /**
     * Retrieve an organization role
     * 
     * <p>Use this request to retrieve an existing organization role by its ID.
     * 
     * @param organizationRoleId The ID of the organization role
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetOrganizationRoleResponse get(String organizationRoleId, Optional<Options> options) {
        GetOrganizationRoleRequest request =
            GetOrganizationRoleRequest
                .builder()
                .organizationRoleId(organizationRoleId)
                .build();
        RequestOperation<GetOrganizationRoleRequest, GetOrganizationRoleResponse> operation
              = new GetOrganizationRole.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update an organization role
     * 
     * <p>Updates an existing organization role.
     * You can update the name, key, description, and permissions of the role.
     * All parameters are optional - you can update only the fields you want to change.
     * If the role is used as a creator role or domain default role, updating the key will cascade the
     * update to the organization settings.
     * 
     * @return The call builder
     */
    public UpdateOrganizationRoleRequestBuilder update() {
        return new UpdateOrganizationRoleRequestBuilder(sdkConfiguration);
    }

    /**
     * Update an organization role
     * 
     * <p>Updates an existing organization role.
     * You can update the name, key, description, and permissions of the role.
     * All parameters are optional - you can update only the fields you want to change.
     * If the role is used as a creator role or domain default role, updating the key will cascade the
     * update to the organization settings.
     * 
     * @param organizationRoleId The ID of the organization role to update
     * @param requestBody 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateOrganizationRoleResponse update(String organizationRoleId, UpdateOrganizationRoleRequestBody requestBody) {
        return update(organizationRoleId, requestBody, Optional.empty());
    }

    /**
     * Update an organization role
     * 
     * <p>Updates an existing organization role.
     * You can update the name, key, description, and permissions of the role.
     * All parameters are optional - you can update only the fields you want to change.
     * If the role is used as a creator role or domain default role, updating the key will cascade the
     * update to the organization settings.
     * 
     * @param organizationRoleId The ID of the organization role to update
     * @param requestBody 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateOrganizationRoleResponse update(
            String organizationRoleId, UpdateOrganizationRoleRequestBody requestBody,
            Optional<Options> options) {
        UpdateOrganizationRoleRequest request =
            UpdateOrganizationRoleRequest
                .builder()
                .organizationRoleId(organizationRoleId)
                .requestBody(requestBody)
                .build();
        RequestOperation<UpdateOrganizationRoleRequest, UpdateOrganizationRoleResponse> operation
              = new UpdateOrganizationRole.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete an organization role
     * 
     * <p>Deletes the organization role.
     * The role cannot be deleted if it is currently used as the default creator role, domain default role,
     * assigned to any members, or exists in any invitations.
     * 
     * @return The call builder
     */
    public DeleteOrganizationRoleRequestBuilder delete() {
        return new DeleteOrganizationRoleRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete an organization role
     * 
     * <p>Deletes the organization role.
     * The role cannot be deleted if it is currently used as the default creator role, domain default role,
     * assigned to any members, or exists in any invitations.
     * 
     * @param organizationRoleId The ID of the organization role to delete
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteOrganizationRoleResponse delete(String organizationRoleId) {
        return delete(organizationRoleId, Optional.empty());
    }

    /**
     * Delete an organization role
     * 
     * <p>Deletes the organization role.
     * The role cannot be deleted if it is currently used as the default creator role, domain default role,
     * assigned to any members, or exists in any invitations.
     * 
     * @param organizationRoleId The ID of the organization role to delete
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteOrganizationRoleResponse delete(String organizationRoleId, Optional<Options> options) {
        DeleteOrganizationRoleRequest request =
            DeleteOrganizationRoleRequest
                .builder()
                .organizationRoleId(organizationRoleId)
                .build();
        RequestOperation<DeleteOrganizationRoleRequest, DeleteOrganizationRoleResponse> operation
              = new DeleteOrganizationRole.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Assign a permission to an organization role
     * 
     * <p>Assigns a permission to an organization role
     * 
     * @return The call builder
     */
    public AssignPermissionToOrganizationRoleRequestBuilder assignPermission() {
        return new AssignPermissionToOrganizationRoleRequestBuilder(sdkConfiguration);
    }

    /**
     * Assign a permission to an organization role
     * 
     * <p>Assigns a permission to an organization role
     * 
     * @param organizationRoleId The ID of the organization role
     * @param permissionId The ID of the permission to assign
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AssignPermissionToOrganizationRoleResponse assignPermission(String organizationRoleId, String permissionId) {
        return assignPermission(organizationRoleId, permissionId, Optional.empty());
    }

    /**
     * Assign a permission to an organization role
     * 
     * <p>Assigns a permission to an organization role
     * 
     * @param organizationRoleId The ID of the organization role
     * @param permissionId The ID of the permission to assign
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AssignPermissionToOrganizationRoleResponse assignPermission(
            String organizationRoleId, String permissionId,
            Optional<Options> options) {
        AssignPermissionToOrganizationRoleRequest request =
            AssignPermissionToOrganizationRoleRequest
                .builder()
                .organizationRoleId(organizationRoleId)
                .permissionId(permissionId)
                .build();
        RequestOperation<AssignPermissionToOrganizationRoleRequest, AssignPermissionToOrganizationRoleResponse> operation
              = new AssignPermissionToOrganizationRole.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Remove a permission from an organization role
     * 
     * <p>Removes a permission from an organization role
     * 
     * @return The call builder
     */
    public RemovePermissionFromOrganizationRoleRequestBuilder removePermission() {
        return new RemovePermissionFromOrganizationRoleRequestBuilder(sdkConfiguration);
    }

    /**
     * Remove a permission from an organization role
     * 
     * <p>Removes a permission from an organization role
     * 
     * @param organizationRoleId The ID of the organization role
     * @param permissionId The ID of the permission to remove
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RemovePermissionFromOrganizationRoleResponse removePermission(String organizationRoleId, String permissionId) {
        return removePermission(organizationRoleId, permissionId, Optional.empty());
    }

    /**
     * Remove a permission from an organization role
     * 
     * <p>Removes a permission from an organization role
     * 
     * @param organizationRoleId The ID of the organization role
     * @param permissionId The ID of the permission to remove
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RemovePermissionFromOrganizationRoleResponse removePermission(
            String organizationRoleId, String permissionId,
            Optional<Options> options) {
        RemovePermissionFromOrganizationRoleRequest request =
            RemovePermissionFromOrganizationRoleRequest
                .builder()
                .organizationRoleId(organizationRoleId)
                .permissionId(permissionId)
                .build();
        RequestOperation<RemovePermissionFromOrganizationRoleRequest, RemovePermissionFromOrganizationRoleResponse> operation
              = new RemovePermissionFromOrganizationRole.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
