/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;


public class BillingPaymentAttemptPayer {

    @JsonProperty("remaining_balance")
    private CommerceMoneyResponse remainingBalance;


    @JsonProperty("applied_amount")
    private CommerceMoneyResponse appliedAmount;

    @JsonCreator
    public BillingPaymentAttemptPayer(
            @JsonProperty("remaining_balance") CommerceMoneyResponse remainingBalance,
            @JsonProperty("applied_amount") CommerceMoneyResponse appliedAmount) {
        Utils.checkNotNull(remainingBalance, "remainingBalance");
        Utils.checkNotNull(appliedAmount, "appliedAmount");
        this.remainingBalance = remainingBalance;
        this.appliedAmount = appliedAmount;
    }

    @JsonIgnore
    public CommerceMoneyResponse remainingBalance() {
        return remainingBalance;
    }

    @JsonIgnore
    public CommerceMoneyResponse appliedAmount() {
        return appliedAmount;
    }

    public static Builder builder() {
        return new Builder();
    }


    public BillingPaymentAttemptPayer withRemainingBalance(CommerceMoneyResponse remainingBalance) {
        Utils.checkNotNull(remainingBalance, "remainingBalance");
        this.remainingBalance = remainingBalance;
        return this;
    }

    public BillingPaymentAttemptPayer withAppliedAmount(CommerceMoneyResponse appliedAmount) {
        Utils.checkNotNull(appliedAmount, "appliedAmount");
        this.appliedAmount = appliedAmount;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BillingPaymentAttemptPayer other = (BillingPaymentAttemptPayer) o;
        return 
            Utils.enhancedDeepEquals(this.remainingBalance, other.remainingBalance) &&
            Utils.enhancedDeepEquals(this.appliedAmount, other.appliedAmount);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            remainingBalance, appliedAmount);
    }
    
    @Override
    public String toString() {
        return Utils.toString(BillingPaymentAttemptPayer.class,
                "remainingBalance", remainingBalance,
                "appliedAmount", appliedAmount);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private CommerceMoneyResponse remainingBalance;

        private CommerceMoneyResponse appliedAmount;

        private Builder() {
          // force use of static builder() method
        }


        public Builder remainingBalance(CommerceMoneyResponse remainingBalance) {
            Utils.checkNotNull(remainingBalance, "remainingBalance");
            this.remainingBalance = remainingBalance;
            return this;
        }


        public Builder appliedAmount(CommerceMoneyResponse appliedAmount) {
            Utils.checkNotNull(appliedAmount, "appliedAmount");
            this.appliedAmount = appliedAmount;
            return this;
        }

        public BillingPaymentAttemptPayer build() {

            return new BillingPaymentAttemptPayer(
                remainingBalance, appliedAmount);
        }

    }
}
