/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CommerceSubscriptionItemStatus
 * 
 * <p>Current status of the subscription item.
 */
public enum CommerceSubscriptionItemStatus {
    ACTIVE("active"),
    ENDED("ended"),
    PAST_DUE("past_due"),
    UPCOMING("upcoming"),
    INCOMPLETE("incomplete"),
    ABANDONED("abandoned");

    @JsonValue
    private final String value;

    CommerceSubscriptionItemStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CommerceSubscriptionItemStatus> fromValue(String value) {
        for (CommerceSubscriptionItemStatus o: CommerceSubscriptionItemStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

