/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CommercePlan2Object
 * 
 * <p>String representing the object's type. Objects of the same type share the same value.
 */
public enum CommercePlan2Object {
    COMMERCE_PLAN("commerce_plan");

    @JsonValue
    private final String value;

    CommercePlan2Object(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CommercePlan2Object> fromValue(String value) {
        for (CommercePlan2Object o: CommercePlan2Object.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

