/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.clerk.backend_api.models.components;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
public enum Crv {
    ED25519("Ed25519");

    @JsonValue
    private final String value;

    private Crv(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Crv> fromValue(String value) {
        for (Crv o: Crv.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
