/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * Effect
 * 
 * <p>The snapshotted discount effect.
 */
public enum Effect {
    PERCENTAGE("percentage"),
    FIXED_AMOUNT("fixed_amount");

    @JsonValue
    private final String value;

    Effect(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Effect> fromValue(String value) {
        for (Effect o: Effect.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

