/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;

/**
 * InstanceProtect
 * 
 * <p>Success
 */
public class InstanceProtect {

    @JsonProperty("object")
    private InstanceProtectObject object;


    @JsonProperty("rules_enabled")
    private boolean rulesEnabled;


    @JsonProperty("specter_enabled")
    private boolean specterEnabled;

    @JsonCreator
    public InstanceProtect(
            @JsonProperty("object") InstanceProtectObject object,
            @JsonProperty("rules_enabled") boolean rulesEnabled,
            @JsonProperty("specter_enabled") boolean specterEnabled) {
        Utils.checkNotNull(object, "object");
        Utils.checkNotNull(rulesEnabled, "rulesEnabled");
        Utils.checkNotNull(specterEnabled, "specterEnabled");
        this.object = object;
        this.rulesEnabled = rulesEnabled;
        this.specterEnabled = specterEnabled;
    }

    @JsonIgnore
    public InstanceProtectObject object() {
        return object;
    }

    @JsonIgnore
    public boolean rulesEnabled() {
        return rulesEnabled;
    }

    @JsonIgnore
    public boolean specterEnabled() {
        return specterEnabled;
    }

    public static Builder builder() {
        return new Builder();
    }


    public InstanceProtect withObject(InstanceProtectObject object) {
        Utils.checkNotNull(object, "object");
        this.object = object;
        return this;
    }

    public InstanceProtect withRulesEnabled(boolean rulesEnabled) {
        Utils.checkNotNull(rulesEnabled, "rulesEnabled");
        this.rulesEnabled = rulesEnabled;
        return this;
    }

    public InstanceProtect withSpecterEnabled(boolean specterEnabled) {
        Utils.checkNotNull(specterEnabled, "specterEnabled");
        this.specterEnabled = specterEnabled;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InstanceProtect other = (InstanceProtect) o;
        return 
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.rulesEnabled, other.rulesEnabled) &&
            Utils.enhancedDeepEquals(this.specterEnabled, other.specterEnabled);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            object, rulesEnabled, specterEnabled);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InstanceProtect.class,
                "object", object,
                "rulesEnabled", rulesEnabled,
                "specterEnabled", specterEnabled);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private InstanceProtectObject object;

        private Boolean rulesEnabled;

        private Boolean specterEnabled;

        private Builder() {
          // force use of static builder() method
        }


        public Builder object(InstanceProtectObject object) {
            Utils.checkNotNull(object, "object");
            this.object = object;
            return this;
        }


        public Builder rulesEnabled(boolean rulesEnabled) {
            Utils.checkNotNull(rulesEnabled, "rulesEnabled");
            this.rulesEnabled = rulesEnabled;
            return this;
        }


        public Builder specterEnabled(boolean specterEnabled) {
            Utils.checkNotNull(specterEnabled, "specterEnabled");
            this.specterEnabled = specterEnabled;
            return this;
        }

        public InstanceProtect build() {

            return new InstanceProtect(
                object, rulesEnabled, specterEnabled);
        }

    }
}
