/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class Logs {

    @JsonProperty("level")
    private String level;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    private Optional<String> code;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("short_message")
    private Optional<String> shortMessage;


    @JsonProperty("message")
    private String message;

    @JsonCreator
    public Logs(
            @JsonProperty("level") String level,
            @JsonProperty("code") Optional<String> code,
            @JsonProperty("short_message") Optional<String> shortMessage,
            @JsonProperty("message") String message) {
        Utils.checkNotNull(level, "level");
        Utils.checkNotNull(code, "code");
        Utils.checkNotNull(shortMessage, "shortMessage");
        Utils.checkNotNull(message, "message");
        this.level = level;
        this.code = code;
        this.shortMessage = shortMessage;
        this.message = message;
    }
    
    public Logs(
            String level,
            String message) {
        this(level, Optional.empty(), Optional.empty(),
            message);
    }

    @JsonIgnore
    public String level() {
        return level;
    }

    @JsonIgnore
    public Optional<String> code() {
        return code;
    }

    @JsonIgnore
    public Optional<String> shortMessage() {
        return shortMessage;
    }

    @JsonIgnore
    public String message() {
        return message;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Logs withLevel(String level) {
        Utils.checkNotNull(level, "level");
        this.level = level;
        return this;
    }

    public Logs withCode(String code) {
        Utils.checkNotNull(code, "code");
        this.code = Optional.ofNullable(code);
        return this;
    }


    public Logs withCode(Optional<String> code) {
        Utils.checkNotNull(code, "code");
        this.code = code;
        return this;
    }

    public Logs withShortMessage(String shortMessage) {
        Utils.checkNotNull(shortMessage, "shortMessage");
        this.shortMessage = Optional.ofNullable(shortMessage);
        return this;
    }


    public Logs withShortMessage(Optional<String> shortMessage) {
        Utils.checkNotNull(shortMessage, "shortMessage");
        this.shortMessage = shortMessage;
        return this;
    }

    public Logs withMessage(String message) {
        Utils.checkNotNull(message, "message");
        this.message = message;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Logs other = (Logs) o;
        return 
            Utils.enhancedDeepEquals(this.level, other.level) &&
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.shortMessage, other.shortMessage) &&
            Utils.enhancedDeepEquals(this.message, other.message);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            level, code, shortMessage,
            message);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Logs.class,
                "level", level,
                "code", code,
                "shortMessage", shortMessage,
                "message", message);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String level;

        private Optional<String> code = Optional.empty();

        private Optional<String> shortMessage = Optional.empty();

        private String message;

        private Builder() {
          // force use of static builder() method
        }


        public Builder level(String level) {
            Utils.checkNotNull(level, "level");
            this.level = level;
            return this;
        }


        public Builder code(String code) {
            Utils.checkNotNull(code, "code");
            this.code = Optional.ofNullable(code);
            return this;
        }

        public Builder code(Optional<String> code) {
            Utils.checkNotNull(code, "code");
            this.code = code;
            return this;
        }


        public Builder shortMessage(String shortMessage) {
            Utils.checkNotNull(shortMessage, "shortMessage");
            this.shortMessage = Optional.ofNullable(shortMessage);
            return this;
        }

        public Builder shortMessage(Optional<String> shortMessage) {
            Utils.checkNotNull(shortMessage, "shortMessage");
            this.shortMessage = shortMessage;
            return this;
        }


        public Builder message(String message) {
            Utils.checkNotNull(message, "message");
            this.message = message;
            return this;
        }

        public Logs build() {

            return new Logs(
                level, code, shortMessage,
                message);
        }

    }
}
