/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.List;

/**
 * MachineList
 * 
 * <p>Success
 */
public class MachineList {

    @JsonProperty("data")
    private List<Machine> data;

    /**
     * Total number of machines
     */
    @JsonProperty("total_count")
    private long totalCount;

    @JsonCreator
    public MachineList(
            @JsonProperty("data") List<Machine> data,
            @JsonProperty("total_count") long totalCount) {
        Utils.checkNotNull(data, "data");
        Utils.checkNotNull(totalCount, "totalCount");
        this.data = data;
        this.totalCount = totalCount;
    }

    @JsonIgnore
    public List<Machine> data() {
        return data;
    }

    /**
     * Total number of machines
     */
    @JsonIgnore
    public long totalCount() {
        return totalCount;
    }

    public static Builder builder() {
        return new Builder();
    }


    public MachineList withData(List<Machine> data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
        return this;
    }

    /**
     * Total number of machines
     */
    public MachineList withTotalCount(long totalCount) {
        Utils.checkNotNull(totalCount, "totalCount");
        this.totalCount = totalCount;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MachineList other = (MachineList) o;
        return 
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.totalCount, other.totalCount);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            data, totalCount);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MachineList.class,
                "data", data,
                "totalCount", totalCount);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<Machine> data;

        private Long totalCount;

        private Builder() {
          // force use of static builder() method
        }


        public Builder data(List<Machine> data) {
            Utils.checkNotNull(data, "data");
            this.data = data;
            return this;
        }


        /**
         * Total number of machines
         */
        public Builder totalCount(long totalCount) {
            Utils.checkNotNull(totalCount, "totalCount");
            this.totalCount = totalCount;
            return this;
        }

        public MachineList build() {

            return new MachineList(
                data, totalCount);
        }

    }
}
