/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum OAuthAccessTokenObject {
    OAUTH_ACCESS_TOKEN("oauth_access_token");

    @JsonValue
    private final String value;

    OAuthAccessTokenObject(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<OAuthAccessTokenObject> fromValue(String value) {
        for (OAuthAccessTokenObject o: OAuthAccessTokenObject.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

