/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * OrganizationInvitationPublicUserData
 * 
 * <p>An organization inviter's public user data
 */
public class OrganizationInvitationPublicUserData {

    @JsonProperty("user_id")
    private String userId;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("first_name")
    private Optional<String> firstName;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("last_name")
    private Optional<String> lastName;


    @JsonProperty("image_url")
    private String imageUrl;


    @JsonProperty("has_image")
    private boolean hasImage;


    @JsonProperty("identifier")
    private String identifier;

    @JsonCreator
    public OrganizationInvitationPublicUserData(
            @JsonProperty("user_id") String userId,
            @JsonProperty("first_name") Optional<String> firstName,
            @JsonProperty("last_name") Optional<String> lastName,
            @JsonProperty("image_url") String imageUrl,
            @JsonProperty("has_image") boolean hasImage,
            @JsonProperty("identifier") String identifier) {
        Utils.checkNotNull(userId, "userId");
        Utils.checkNotNull(firstName, "firstName");
        Utils.checkNotNull(lastName, "lastName");
        Utils.checkNotNull(imageUrl, "imageUrl");
        Utils.checkNotNull(hasImage, "hasImage");
        Utils.checkNotNull(identifier, "identifier");
        this.userId = userId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.imageUrl = imageUrl;
        this.hasImage = hasImage;
        this.identifier = identifier;
    }
    
    public OrganizationInvitationPublicUserData(
            String userId,
            String imageUrl,
            boolean hasImage,
            String identifier) {
        this(userId, Optional.empty(), Optional.empty(),
            imageUrl, hasImage, identifier);
    }

    @JsonIgnore
    public String userId() {
        return userId;
    }

    @JsonIgnore
    public Optional<String> firstName() {
        return firstName;
    }

    @JsonIgnore
    public Optional<String> lastName() {
        return lastName;
    }

    @JsonIgnore
    public String imageUrl() {
        return imageUrl;
    }

    @JsonIgnore
    public boolean hasImage() {
        return hasImage;
    }

    @JsonIgnore
    public String identifier() {
        return identifier;
    }

    public static Builder builder() {
        return new Builder();
    }


    public OrganizationInvitationPublicUserData withUserId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }

    public OrganizationInvitationPublicUserData withFirstName(String firstName) {
        Utils.checkNotNull(firstName, "firstName");
        this.firstName = Optional.ofNullable(firstName);
        return this;
    }


    public OrganizationInvitationPublicUserData withFirstName(Optional<String> firstName) {
        Utils.checkNotNull(firstName, "firstName");
        this.firstName = firstName;
        return this;
    }

    public OrganizationInvitationPublicUserData withLastName(String lastName) {
        Utils.checkNotNull(lastName, "lastName");
        this.lastName = Optional.ofNullable(lastName);
        return this;
    }


    public OrganizationInvitationPublicUserData withLastName(Optional<String> lastName) {
        Utils.checkNotNull(lastName, "lastName");
        this.lastName = lastName;
        return this;
    }

    public OrganizationInvitationPublicUserData withImageUrl(String imageUrl) {
        Utils.checkNotNull(imageUrl, "imageUrl");
        this.imageUrl = imageUrl;
        return this;
    }

    public OrganizationInvitationPublicUserData withHasImage(boolean hasImage) {
        Utils.checkNotNull(hasImage, "hasImage");
        this.hasImage = hasImage;
        return this;
    }

    public OrganizationInvitationPublicUserData withIdentifier(String identifier) {
        Utils.checkNotNull(identifier, "identifier");
        this.identifier = identifier;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrganizationInvitationPublicUserData other = (OrganizationInvitationPublicUserData) o;
        return 
            Utils.enhancedDeepEquals(this.userId, other.userId) &&
            Utils.enhancedDeepEquals(this.firstName, other.firstName) &&
            Utils.enhancedDeepEquals(this.lastName, other.lastName) &&
            Utils.enhancedDeepEquals(this.imageUrl, other.imageUrl) &&
            Utils.enhancedDeepEquals(this.hasImage, other.hasImage) &&
            Utils.enhancedDeepEquals(this.identifier, other.identifier);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            userId, firstName, lastName,
            imageUrl, hasImage, identifier);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OrganizationInvitationPublicUserData.class,
                "userId", userId,
                "firstName", firstName,
                "lastName", lastName,
                "imageUrl", imageUrl,
                "hasImage", hasImage,
                "identifier", identifier);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String userId;

        private Optional<String> firstName = Optional.empty();

        private Optional<String> lastName = Optional.empty();

        private String imageUrl;

        private Boolean hasImage;

        private String identifier;

        private Builder() {
          // force use of static builder() method
        }


        public Builder userId(String userId) {
            Utils.checkNotNull(userId, "userId");
            this.userId = userId;
            return this;
        }


        public Builder firstName(String firstName) {
            Utils.checkNotNull(firstName, "firstName");
            this.firstName = Optional.ofNullable(firstName);
            return this;
        }

        public Builder firstName(Optional<String> firstName) {
            Utils.checkNotNull(firstName, "firstName");
            this.firstName = firstName;
            return this;
        }


        public Builder lastName(String lastName) {
            Utils.checkNotNull(lastName, "lastName");
            this.lastName = Optional.ofNullable(lastName);
            return this;
        }

        public Builder lastName(Optional<String> lastName) {
            Utils.checkNotNull(lastName, "lastName");
            this.lastName = lastName;
            return this;
        }


        public Builder imageUrl(String imageUrl) {
            Utils.checkNotNull(imageUrl, "imageUrl");
            this.imageUrl = imageUrl;
            return this;
        }


        public Builder hasImage(boolean hasImage) {
            Utils.checkNotNull(hasImage, "hasImage");
            this.hasImage = hasImage;
            return this;
        }


        public Builder identifier(String identifier) {
            Utils.checkNotNull(identifier, "identifier");
            this.identifier = identifier;
            return this;
        }

        public OrganizationInvitationPublicUserData build() {

            return new OrganizationInvitationPublicUserData(
                userId, firstName, lastName,
                imageUrl, hasImage, identifier);
        }

    }
}
