/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.components;

import com.clerk.backend_api.utils.GenericTypeIdResolver;
import java.lang.IllegalArgumentException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;


public class PhoneNumberVerificationTypeIdResolver extends GenericTypeIdResolver<PhoneNumberVerification> {

    public PhoneNumberVerificationTypeIdResolver() {
        super(UnknownPhoneNumberVerification.class);
        initializeTypeMap();
    }

    private void initializeTypeMap() {
        registerType("verification_otp", VerificationOTP.class);
        registerType("verification_admin", VerificationAdmin.class);
    }

    @Override
    public String idFromValue(Object value) {
        if (value == null) {
            return null;
        }
        
        // Handle known types by checking if they implement the discriminator method
        if (value instanceof PhoneNumberVerification) {
            PhoneNumberVerification discriminated = (PhoneNumberVerification) value;
            return discriminated.object();
        }
        
        throw new IllegalArgumentException("Unknown value type: " + value.getClass().getName());
    }

    @Override
    public String getDescForKnownTypeIds() {
        return "PhoneNumberVerification type resolver";
    }

}