/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * SchemasCommerceSubscriptionItemPaymentSourceObject
 * 
 * <p>String representing the object's type. Objects of the same type share the same value.
 */
public enum SchemasCommerceSubscriptionItemPaymentSourceObject {
    COMMERCE_SOURCE("commerce_source");

    @JsonValue
    private final String value;

    SchemasCommerceSubscriptionItemPaymentSourceObject(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SchemasCommerceSubscriptionItemPaymentSourceObject> fromValue(String value) {
        for (SchemasCommerceSubscriptionItemPaymentSourceObject o: SchemasCommerceSubscriptionItemPaymentSourceObject.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

