/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * SchemasCommerceSubscriptionItemPlanPeriod
 * 
 * <p>The billing period for this subscription.
 */
public enum SchemasCommerceSubscriptionItemPlanPeriod {
    MONTH("month"),
    ANNUAL("annual");

    @JsonValue
    private final String value;

    SchemasCommerceSubscriptionItemPlanPeriod(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SchemasCommerceSubscriptionItemPlanPeriod> fromValue(String value) {
        for (SchemasCommerceSubscriptionItemPlanPeriod o: SchemasCommerceSubscriptionItemPlanPeriod.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

