/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>Wrapper class for an "open" enum. "Open" enums are those that are expected
 * to evolve (particularly with the addition of enum members over time). If an
 * open enum is used then the appearance of unexpected enum values (say in a 
 * response from an updated API) will not bring about a runtime error thus 
 * ensuring that non-updated client versions can continue to work without error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe
 * cache is maintained to ensure that). As a consequence instances created with the 
 * same value will satisfy reference equality (via {@code ==}).
 * 
 * <p>This class is intended to emulate an enum (in terms of common usage and with 
 * reference equality) but with the ability to carry unknown values. Unfortunately
 * Java does not permit the use of an instance in a switch expression but you can 
 * use the {@code asEnum()} method (after dealing with the `Optional` appropriately).
 *
 */
@JsonDeserialize(using = VerificationOtpVerificationStrategy._Deserializer.class)
@JsonSerialize(using = VerificationOtpVerificationStrategy._Serializer.class)
public class VerificationOtpVerificationStrategy {

    public static final VerificationOtpVerificationStrategy PHONE_CODE = new VerificationOtpVerificationStrategy("phone_code");
    public static final VerificationOtpVerificationStrategy EMAIL_CODE = new VerificationOtpVerificationStrategy("email_code");
    public static final VerificationOtpVerificationStrategy RESET_PASSWORD_EMAIL_CODE = new VerificationOtpVerificationStrategy("reset_password_email_code");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, VerificationOtpVerificationStrategy> values = createValuesMap();
    private static final Map<String, VerificationOtpVerificationStrategyEnum> enums = createEnumsMap();

    private final String value;

    private VerificationOtpVerificationStrategy(String value) {
        this.value = value;
    }

    /**
     * Returns a VerificationOtpVerificationStrategy with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as VerificationOtpVerificationStrategy
     */ 
    public static VerificationOtpVerificationStrategy of(String value) {
        synchronized (VerificationOtpVerificationStrategy.class) {
            return values.computeIfAbsent(value, v -> new VerificationOtpVerificationStrategy(v));
        }
    }

    public String value() {
        return value;
    }

    public Optional<VerificationOtpVerificationStrategyEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        VerificationOtpVerificationStrategy other = (VerificationOtpVerificationStrategy) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "VerificationOtpVerificationStrategy [value=" + value + "]";
    }

    // return an array just like an enum
    public static VerificationOtpVerificationStrategy[] values() {
        synchronized (VerificationOtpVerificationStrategy.class) {
            return values.values().toArray(new VerificationOtpVerificationStrategy[] {});
        }
    }

    private static final Map<String, VerificationOtpVerificationStrategy> createValuesMap() {
        Map<String, VerificationOtpVerificationStrategy> map = new LinkedHashMap<>();
        map.put("phone_code", PHONE_CODE);
        map.put("email_code", EMAIL_CODE);
        map.put("reset_password_email_code", RESET_PASSWORD_EMAIL_CODE);
        return map;
    }

    private static final Map<String, VerificationOtpVerificationStrategyEnum> createEnumsMap() {
        Map<String, VerificationOtpVerificationStrategyEnum> map = new HashMap<>();
        map.put("phone_code", VerificationOtpVerificationStrategyEnum.PHONE_CODE);
        map.put("email_code", VerificationOtpVerificationStrategyEnum.EMAIL_CODE);
        map.put("reset_password_email_code", VerificationOtpVerificationStrategyEnum.RESET_PASSWORD_EMAIL_CODE);
        return map;
    }
    
    @SuppressWarnings("serial")
    public static final class _Serializer extends StdSerializer<VerificationOtpVerificationStrategy> {

        protected _Serializer() {
            super(VerificationOtpVerificationStrategy.class);
        }

        @Override
        public void serialize(VerificationOtpVerificationStrategy value, JsonGenerator g, SerializerProvider provider)
                throws IOException, JsonProcessingException {
            g.writeObject(value.value);
        }
    }

    @SuppressWarnings("serial")
    public static final class _Deserializer extends StdDeserializer<VerificationOtpVerificationStrategy> {

        protected _Deserializer() {
            super(VerificationOtpVerificationStrategy.class);
        }

        @Override
        public VerificationOtpVerificationStrategy deserialize(JsonParser p, DeserializationContext ctxt)
                throws IOException, JacksonException {
            String v = p.readValueAs(new TypeReference<String>() {});
            // use the factory method to ensure we get singletons
            return VerificationOtpVerificationStrategy.of(v);
        }
    }
    
    public enum VerificationOtpVerificationStrategyEnum {

        PHONE_CODE("phone_code"),
        EMAIL_CODE("email_code"),
        RESET_PASSWORD_EMAIL_CODE("reset_password_email_code"),;

        private final String value;

        private VerificationOtpVerificationStrategyEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

