/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum Web3SignatureVerificationStrategy {
    WEB3_METAMASK_SIGNATURE("web3_metamask_signature"),
    WEB3_COINBASE_WALLET_SIGNATURE("web3_coinbase_wallet_signature"),
    WEB3_OKX_WALLET_SIGNATURE("web3_okx_wallet_signature");

    @JsonValue
    private final String value;

    private Web3SignatureVerificationStrategy(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Web3SignatureVerificationStrategy> fromValue(String value) {
        for (Web3SignatureVerificationStrategy o: Web3SignatureVerificationStrategy.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
