workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    clerk-java-sdk:
        inputs:
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/bapi/2025-04-10.yml
        overlays:
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/.speakeasy/bapi/fixes.yml
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-java-sdk
targets:
    clerk-java:
        target: java
        source: clerk-java-sdk
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $gpg_secret_key
                gpgPassPhrase: $gpg_pass_phrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/clerk/clerk/clerk-java-sdk-code-samples
            blocking: false
