/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class CreateRoleSetRequestBody {
    /**
     * The name of the new role set
     */
    @JsonProperty("name")
    private String name;

    /**
     * A unique key for the role set. Must start with 'role_set:' and contain only lowercase alphanumeric
     * characters and underscores.
     * If not provided, a key will be generated from the name.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("key")
    private Optional<String> key;

    /**
     * Optional description for the role set
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private JsonNullable<String> description;

    /**
     * The key of the role to use as the default role for new organization members.
     * Must be one of the roles in the `roles` array.
     */
    @JsonProperty("default_role_key")
    private String defaultRoleKey;

    /**
     * The key of the role to assign to organization creators.
     * Must be one of the roles in the `roles` array.
     */
    @JsonProperty("creator_role_key")
    private String creatorRoleKey;

    /**
     * The type of the role set. "initial" role sets are the default for new organizations.
     * Only one role set can be "initial" per instance.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private Optional<? extends Type> type;

    /**
     * Array of role keys to include in the role set.
     * Must contain at least one role and no more than 10 roles.
     */
    @JsonProperty("roles")
    private List<String> roles;

    @JsonCreator
    public CreateRoleSetRequestBody(
            @JsonProperty("name") String name,
            @JsonProperty("key") Optional<String> key,
            @JsonProperty("description") JsonNullable<String> description,
            @JsonProperty("default_role_key") String defaultRoleKey,
            @JsonProperty("creator_role_key") String creatorRoleKey,
            @JsonProperty("type") Optional<? extends Type> type,
            @JsonProperty("roles") List<String> roles) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(key, "key");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(defaultRoleKey, "defaultRoleKey");
        Utils.checkNotNull(creatorRoleKey, "creatorRoleKey");
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(roles, "roles");
        this.name = name;
        this.key = key;
        this.description = description;
        this.defaultRoleKey = defaultRoleKey;
        this.creatorRoleKey = creatorRoleKey;
        this.type = type;
        this.roles = roles;
    }
    
    public CreateRoleSetRequestBody(
            String name,
            String defaultRoleKey,
            String creatorRoleKey,
            List<String> roles) {
        this(name, Optional.empty(), JsonNullable.undefined(),
            defaultRoleKey, creatorRoleKey, Optional.empty(),
            roles);
    }

    /**
     * The name of the new role set
     */
    @JsonIgnore
    public String name() {
        return name;
    }

    /**
     * A unique key for the role set. Must start with 'role_set:' and contain only lowercase alphanumeric
     * characters and underscores.
     * If not provided, a key will be generated from the name.
     */
    @JsonIgnore
    public Optional<String> key() {
        return key;
    }

    /**
     * Optional description for the role set
     */
    @JsonIgnore
    public JsonNullable<String> description() {
        return description;
    }

    /**
     * The key of the role to use as the default role for new organization members.
     * Must be one of the roles in the `roles` array.
     */
    @JsonIgnore
    public String defaultRoleKey() {
        return defaultRoleKey;
    }

    /**
     * The key of the role to assign to organization creators.
     * Must be one of the roles in the `roles` array.
     */
    @JsonIgnore
    public String creatorRoleKey() {
        return creatorRoleKey;
    }

    /**
     * The type of the role set. "initial" role sets are the default for new organizations.
     * Only one role set can be "initial" per instance.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Type> type() {
        return (Optional<Type>) type;
    }

    /**
     * Array of role keys to include in the role set.
     * Must contain at least one role and no more than 10 roles.
     */
    @JsonIgnore
    public List<String> roles() {
        return roles;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the new role set
     */
    public CreateRoleSetRequestBody withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * A unique key for the role set. Must start with 'role_set:' and contain only lowercase alphanumeric
     * characters and underscores.
     * If not provided, a key will be generated from the name.
     */
    public CreateRoleSetRequestBody withKey(String key) {
        Utils.checkNotNull(key, "key");
        this.key = Optional.ofNullable(key);
        return this;
    }


    /**
     * A unique key for the role set. Must start with 'role_set:' and contain only lowercase alphanumeric
     * characters and underscores.
     * If not provided, a key will be generated from the name.
     */
    public CreateRoleSetRequestBody withKey(Optional<String> key) {
        Utils.checkNotNull(key, "key");
        this.key = key;
        return this;
    }

    /**
     * Optional description for the role set
     */
    public CreateRoleSetRequestBody withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = JsonNullable.of(description);
        return this;
    }

    /**
     * Optional description for the role set
     */
    public CreateRoleSetRequestBody withDescription(JsonNullable<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    /**
     * The key of the role to use as the default role for new organization members.
     * Must be one of the roles in the `roles` array.
     */
    public CreateRoleSetRequestBody withDefaultRoleKey(String defaultRoleKey) {
        Utils.checkNotNull(defaultRoleKey, "defaultRoleKey");
        this.defaultRoleKey = defaultRoleKey;
        return this;
    }

    /**
     * The key of the role to assign to organization creators.
     * Must be one of the roles in the `roles` array.
     */
    public CreateRoleSetRequestBody withCreatorRoleKey(String creatorRoleKey) {
        Utils.checkNotNull(creatorRoleKey, "creatorRoleKey");
        this.creatorRoleKey = creatorRoleKey;
        return this;
    }

    /**
     * The type of the role set. "initial" role sets are the default for new organizations.
     * Only one role set can be "initial" per instance.
     */
    public CreateRoleSetRequestBody withType(Type type) {
        Utils.checkNotNull(type, "type");
        this.type = Optional.ofNullable(type);
        return this;
    }


    /**
     * The type of the role set. "initial" role sets are the default for new organizations.
     * Only one role set can be "initial" per instance.
     */
    public CreateRoleSetRequestBody withType(Optional<? extends Type> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    /**
     * Array of role keys to include in the role set.
     * Must contain at least one role and no more than 10 roles.
     */
    public CreateRoleSetRequestBody withRoles(List<String> roles) {
        Utils.checkNotNull(roles, "roles");
        this.roles = roles;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateRoleSetRequestBody other = (CreateRoleSetRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.key, other.key) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.defaultRoleKey, other.defaultRoleKey) &&
            Utils.enhancedDeepEquals(this.creatorRoleKey, other.creatorRoleKey) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.roles, other.roles);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, key, description,
            defaultRoleKey, creatorRoleKey, type,
            roles);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateRoleSetRequestBody.class,
                "name", name,
                "key", key,
                "description", description,
                "defaultRoleKey", defaultRoleKey,
                "creatorRoleKey", creatorRoleKey,
                "type", type,
                "roles", roles);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private Optional<String> key = Optional.empty();

        private JsonNullable<String> description = JsonNullable.undefined();

        private String defaultRoleKey;

        private String creatorRoleKey;

        private Optional<? extends Type> type = Optional.empty();

        private List<String> roles;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The name of the new role set
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        /**
         * A unique key for the role set. Must start with 'role_set:' and contain only lowercase alphanumeric
         * characters and underscores.
         * If not provided, a key will be generated from the name.
         */
        public Builder key(String key) {
            Utils.checkNotNull(key, "key");
            this.key = Optional.ofNullable(key);
            return this;
        }

        /**
         * A unique key for the role set. Must start with 'role_set:' and contain only lowercase alphanumeric
         * characters and underscores.
         * If not provided, a key will be generated from the name.
         */
        public Builder key(Optional<String> key) {
            Utils.checkNotNull(key, "key");
            this.key = key;
            return this;
        }


        /**
         * Optional description for the role set
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = JsonNullable.of(description);
            return this;
        }

        /**
         * Optional description for the role set
         */
        public Builder description(JsonNullable<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }


        /**
         * The key of the role to use as the default role for new organization members.
         * Must be one of the roles in the `roles` array.
         */
        public Builder defaultRoleKey(String defaultRoleKey) {
            Utils.checkNotNull(defaultRoleKey, "defaultRoleKey");
            this.defaultRoleKey = defaultRoleKey;
            return this;
        }


        /**
         * The key of the role to assign to organization creators.
         * Must be one of the roles in the `roles` array.
         */
        public Builder creatorRoleKey(String creatorRoleKey) {
            Utils.checkNotNull(creatorRoleKey, "creatorRoleKey");
            this.creatorRoleKey = creatorRoleKey;
            return this;
        }


        /**
         * The type of the role set. "initial" role sets are the default for new organizations.
         * Only one role set can be "initial" per instance.
         */
        public Builder type(Type type) {
            Utils.checkNotNull(type, "type");
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * The type of the role set. "initial" role sets are the default for new organizations.
         * Only one role set can be "initial" per instance.
         */
        public Builder type(Optional<? extends Type> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }


        /**
         * Array of role keys to include in the role set.
         * Must contain at least one role and no more than 10 roles.
         */
        public Builder roles(List<String> roles) {
            Utils.checkNotNull(roles, "roles");
            this.roles = roles;
            return this;
        }

        public CreateRoleSetRequestBody build() {

            return new CreateRoleSetRequestBody(
                name, key, description,
                defaultRoleKey, creatorRoleKey, type,
                roles);
        }

    }
}
