/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class CreateDirectoryGroupRoleMappingRequestBody {
    /**
     * The group ID from the identity provider. Exactly one of `directory_group_id` or `scim_group_id` is
     * required.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("directory_group_id")
    private Optional<String> directoryGroupId;

    /**
     * The legacy name for `directory_group_id`. Send either one, or both with the same value; sending both
     * with different values is rejected.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scim_group_id")
    private Optional<String> scimGroupId;

    /**
     * The ID of the organization role to assign to members of the group.
     */
    @JsonProperty("role_id")
    private String roleId;

    /**
     * The precedence for this mapping. Lower values take priority when a user belongs
     * to multiple mapped groups. If omitted, the mapping is appended with the
     * next-highest precedence.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("precedence")
    private Optional<Long> precedence;

    @JsonCreator
    public CreateDirectoryGroupRoleMappingRequestBody(
            @JsonProperty("directory_group_id") Optional<String> directoryGroupId,
            @JsonProperty("scim_group_id") Optional<String> scimGroupId,
            @JsonProperty("role_id") String roleId,
            @JsonProperty("precedence") Optional<Long> precedence) {
        Utils.checkNotNull(directoryGroupId, "directoryGroupId");
        Utils.checkNotNull(scimGroupId, "scimGroupId");
        Utils.checkNotNull(roleId, "roleId");
        Utils.checkNotNull(precedence, "precedence");
        this.directoryGroupId = directoryGroupId;
        this.scimGroupId = scimGroupId;
        this.roleId = roleId;
        this.precedence = precedence;
    }
    
    public CreateDirectoryGroupRoleMappingRequestBody(
            String roleId) {
        this(Optional.empty(), Optional.empty(), roleId,
            Optional.empty());
    }

    /**
     * The group ID from the identity provider. Exactly one of `directory_group_id` or `scim_group_id` is
     * required.
     */
    @JsonIgnore
    public Optional<String> directoryGroupId() {
        return directoryGroupId;
    }

    /**
     * The legacy name for `directory_group_id`. Send either one, or both with the same value; sending both
     * with different values is rejected.
     */
    @JsonIgnore
    public Optional<String> scimGroupId() {
        return scimGroupId;
    }

    /**
     * The ID of the organization role to assign to members of the group.
     */
    @JsonIgnore
    public String roleId() {
        return roleId;
    }

    /**
     * The precedence for this mapping. Lower values take priority when a user belongs
     * to multiple mapped groups. If omitted, the mapping is appended with the
     * next-highest precedence.
     */
    @JsonIgnore
    public Optional<Long> precedence() {
        return precedence;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The group ID from the identity provider. Exactly one of `directory_group_id` or `scim_group_id` is
     * required.
     */
    public CreateDirectoryGroupRoleMappingRequestBody withDirectoryGroupId(String directoryGroupId) {
        Utils.checkNotNull(directoryGroupId, "directoryGroupId");
        this.directoryGroupId = Optional.ofNullable(directoryGroupId);
        return this;
    }


    /**
     * The group ID from the identity provider. Exactly one of `directory_group_id` or `scim_group_id` is
     * required.
     */
    public CreateDirectoryGroupRoleMappingRequestBody withDirectoryGroupId(Optional<String> directoryGroupId) {
        Utils.checkNotNull(directoryGroupId, "directoryGroupId");
        this.directoryGroupId = directoryGroupId;
        return this;
    }

    /**
     * The legacy name for `directory_group_id`. Send either one, or both with the same value; sending both
     * with different values is rejected.
     */
    public CreateDirectoryGroupRoleMappingRequestBody withScimGroupId(String scimGroupId) {
        Utils.checkNotNull(scimGroupId, "scimGroupId");
        this.scimGroupId = Optional.ofNullable(scimGroupId);
        return this;
    }


    /**
     * The legacy name for `directory_group_id`. Send either one, or both with the same value; sending both
     * with different values is rejected.
     */
    public CreateDirectoryGroupRoleMappingRequestBody withScimGroupId(Optional<String> scimGroupId) {
        Utils.checkNotNull(scimGroupId, "scimGroupId");
        this.scimGroupId = scimGroupId;
        return this;
    }

    /**
     * The ID of the organization role to assign to members of the group.
     */
    public CreateDirectoryGroupRoleMappingRequestBody withRoleId(String roleId) {
        Utils.checkNotNull(roleId, "roleId");
        this.roleId = roleId;
        return this;
    }

    /**
     * The precedence for this mapping. Lower values take priority when a user belongs
     * to multiple mapped groups. If omitted, the mapping is appended with the
     * next-highest precedence.
     */
    public CreateDirectoryGroupRoleMappingRequestBody withPrecedence(long precedence) {
        Utils.checkNotNull(precedence, "precedence");
        this.precedence = Optional.ofNullable(precedence);
        return this;
    }


    /**
     * The precedence for this mapping. Lower values take priority when a user belongs
     * to multiple mapped groups. If omitted, the mapping is appended with the
     * next-highest precedence.
     */
    public CreateDirectoryGroupRoleMappingRequestBody withPrecedence(Optional<Long> precedence) {
        Utils.checkNotNull(precedence, "precedence");
        this.precedence = precedence;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateDirectoryGroupRoleMappingRequestBody other = (CreateDirectoryGroupRoleMappingRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.directoryGroupId, other.directoryGroupId) &&
            Utils.enhancedDeepEquals(this.scimGroupId, other.scimGroupId) &&
            Utils.enhancedDeepEquals(this.roleId, other.roleId) &&
            Utils.enhancedDeepEquals(this.precedence, other.precedence);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            directoryGroupId, scimGroupId, roleId,
            precedence);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateDirectoryGroupRoleMappingRequestBody.class,
                "directoryGroupId", directoryGroupId,
                "scimGroupId", scimGroupId,
                "roleId", roleId,
                "precedence", precedence);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> directoryGroupId = Optional.empty();

        private Optional<String> scimGroupId = Optional.empty();

        private String roleId;

        private Optional<Long> precedence = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The group ID from the identity provider. Exactly one of `directory_group_id` or `scim_group_id` is
         * required.
         */
        public Builder directoryGroupId(String directoryGroupId) {
            Utils.checkNotNull(directoryGroupId, "directoryGroupId");
            this.directoryGroupId = Optional.ofNullable(directoryGroupId);
            return this;
        }

        /**
         * The group ID from the identity provider. Exactly one of `directory_group_id` or `scim_group_id` is
         * required.
         */
        public Builder directoryGroupId(Optional<String> directoryGroupId) {
            Utils.checkNotNull(directoryGroupId, "directoryGroupId");
            this.directoryGroupId = directoryGroupId;
            return this;
        }


        /**
         * The legacy name for `directory_group_id`. Send either one, or both with the same value; sending both
         * with different values is rejected.
         */
        public Builder scimGroupId(String scimGroupId) {
            Utils.checkNotNull(scimGroupId, "scimGroupId");
            this.scimGroupId = Optional.ofNullable(scimGroupId);
            return this;
        }

        /**
         * The legacy name for `directory_group_id`. Send either one, or both with the same value; sending both
         * with different values is rejected.
         */
        public Builder scimGroupId(Optional<String> scimGroupId) {
            Utils.checkNotNull(scimGroupId, "scimGroupId");
            this.scimGroupId = scimGroupId;
            return this;
        }


        /**
         * The ID of the organization role to assign to members of the group.
         */
        public Builder roleId(String roleId) {
            Utils.checkNotNull(roleId, "roleId");
            this.roleId = roleId;
            return this;
        }


        /**
         * The precedence for this mapping. Lower values take priority when a user belongs
         * to multiple mapped groups. If omitted, the mapping is appended with the
         * next-highest precedence.
         */
        public Builder precedence(long precedence) {
            Utils.checkNotNull(precedence, "precedence");
            this.precedence = Optional.ofNullable(precedence);
            return this;
        }

        /**
         * The precedence for this mapping. Lower values take priority when a user belongs
         * to multiple mapped groups. If omitted, the mapping is appended with the
         * next-highest precedence.
         */
        public Builder precedence(Optional<Long> precedence) {
            Utils.checkNotNull(precedence, "precedence");
            this.precedence = precedence;
            return this;
        }

        public CreateDirectoryGroupRoleMappingRequestBody build() {

            return new CreateDirectoryGroupRoleMappingRequestBody(
                directoryGroupId, scimGroupId, roleId,
                precedence);
        }

    }
}
