/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;


import com.clerk.backend_api.models.components.SAMLConnection;
import com.clerk.backend_api.utils.Response;
import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class CreateSAMLConnectionResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * A SAML Connection
     */
    private Optional<? extends SAMLConnection> samlConnection;

    @JsonCreator
    public CreateSAMLConnectionResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends SAMLConnection> samlConnection) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(samlConnection, "samlConnection");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.samlConnection = samlConnection;
    }
    
    public CreateSAMLConnectionResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * A SAML Connection
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<SAMLConnection> samlConnection() {
        return (Optional<SAMLConnection>) samlConnection;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public CreateSAMLConnectionResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CreateSAMLConnectionResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateSAMLConnectionResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * A SAML Connection
     */
    public CreateSAMLConnectionResponse withSAMLConnection(SAMLConnection samlConnection) {
        Utils.checkNotNull(samlConnection, "samlConnection");
        this.samlConnection = Optional.ofNullable(samlConnection);
        return this;
    }

    /**
     * A SAML Connection
     */
    public CreateSAMLConnectionResponse withSAMLConnection(Optional<? extends SAMLConnection> samlConnection) {
        Utils.checkNotNull(samlConnection, "samlConnection");
        this.samlConnection = samlConnection;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateSAMLConnectionResponse other = (CreateSAMLConnectionResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.samlConnection, other.samlConnection);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            samlConnection);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateSAMLConnectionResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "samlConnection", samlConnection);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends SAMLConnection> samlConnection = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * A SAML Connection
         */
        public Builder samlConnection(SAMLConnection samlConnection) {
            Utils.checkNotNull(samlConnection, "samlConnection");
            this.samlConnection = Optional.ofNullable(samlConnection);
            return this;
        }

        /**
         * A SAML Connection
         */
        public Builder samlConnection(Optional<? extends SAMLConnection> samlConnection) {
            Utils.checkNotNull(samlConnection, "samlConnection");
            this.samlConnection = samlConnection;
            return this;
        }
        
        public CreateSAMLConnectionResponse build() {
            return new CreateSAMLConnectionResponse(
                contentType,
                statusCode,
                rawResponse,
                samlConnection);
        }
    }
}

