/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public class CreateBlocklistIdentifierRequestBody {

    /**
     * The identifier to be added in the block-list.
     * This can be an email address, a phone number or a web3 wallet.
     */
    @JsonProperty("identifier")
    private String identifier;

    @JsonCreator
    public CreateBlocklistIdentifierRequestBody(
            @JsonProperty("identifier") String identifier) {
        Utils.checkNotNull(identifier, "identifier");
        this.identifier = identifier;
    }

    /**
     * The identifier to be added in the block-list.
     * This can be an email address, a phone number or a web3 wallet.
     */
    @JsonIgnore
    public String identifier() {
        return identifier;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The identifier to be added in the block-list.
     * This can be an email address, a phone number or a web3 wallet.
     */
    public CreateBlocklistIdentifierRequestBody withIdentifier(String identifier) {
        Utils.checkNotNull(identifier, "identifier");
        this.identifier = identifier;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateBlocklistIdentifierRequestBody other = (CreateBlocklistIdentifierRequestBody) o;
        return 
            java.util.Objects.deepEquals(this.identifier, other.identifier);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            identifier);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateBlocklistIdentifierRequestBody.class,
                "identifier", identifier);
    }
    
    public final static class Builder {
 
        private String identifier;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The identifier to be added in the block-list.
         * This can be an email address, a phone number or a web3 wallet.
         */
        public Builder identifier(String identifier) {
            Utils.checkNotNull(identifier, "identifier");
            this.identifier = identifier;
            return this;
        }
        
        public CreateBlocklistIdentifierRequestBody build() {
            return new CreateBlocklistIdentifierRequestBody(
                identifier);
        }
    }
}

