/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.models.components.PriceTransitionRequest;
import com.clerk.backend_api.utils.SpeakeasyMetadata;
import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;


public class CreateBillingPriceTransitionRequest {
    /**
     * The ID of the subscription item to transition
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscription_item_id")
    private String subscriptionItemId;

    /**
     * Parameters for the price transition
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private PriceTransitionRequest priceTransitionRequest;

    @JsonCreator
    public CreateBillingPriceTransitionRequest(
            String subscriptionItemId,
            PriceTransitionRequest priceTransitionRequest) {
        Utils.checkNotNull(subscriptionItemId, "subscriptionItemId");
        Utils.checkNotNull(priceTransitionRequest, "priceTransitionRequest");
        this.subscriptionItemId = subscriptionItemId;
        this.priceTransitionRequest = priceTransitionRequest;
    }

    /**
     * The ID of the subscription item to transition
     */
    @JsonIgnore
    public String subscriptionItemId() {
        return subscriptionItemId;
    }

    /**
     * Parameters for the price transition
     */
    @JsonIgnore
    public PriceTransitionRequest priceTransitionRequest() {
        return priceTransitionRequest;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the subscription item to transition
     */
    public CreateBillingPriceTransitionRequest withSubscriptionItemId(String subscriptionItemId) {
        Utils.checkNotNull(subscriptionItemId, "subscriptionItemId");
        this.subscriptionItemId = subscriptionItemId;
        return this;
    }

    /**
     * Parameters for the price transition
     */
    public CreateBillingPriceTransitionRequest withPriceTransitionRequest(PriceTransitionRequest priceTransitionRequest) {
        Utils.checkNotNull(priceTransitionRequest, "priceTransitionRequest");
        this.priceTransitionRequest = priceTransitionRequest;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateBillingPriceTransitionRequest other = (CreateBillingPriceTransitionRequest) o;
        return 
            Utils.enhancedDeepEquals(this.subscriptionItemId, other.subscriptionItemId) &&
            Utils.enhancedDeepEquals(this.priceTransitionRequest, other.priceTransitionRequest);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subscriptionItemId, priceTransitionRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateBillingPriceTransitionRequest.class,
                "subscriptionItemId", subscriptionItemId,
                "priceTransitionRequest", priceTransitionRequest);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String subscriptionItemId;

        private PriceTransitionRequest priceTransitionRequest;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The ID of the subscription item to transition
         */
        public Builder subscriptionItemId(String subscriptionItemId) {
            Utils.checkNotNull(subscriptionItemId, "subscriptionItemId");
            this.subscriptionItemId = subscriptionItemId;
            return this;
        }


        /**
         * Parameters for the price transition
         */
        public Builder priceTransitionRequest(PriceTransitionRequest priceTransitionRequest) {
            Utils.checkNotNull(priceTransitionRequest, "priceTransitionRequest");
            this.priceTransitionRequest = priceTransitionRequest;
            return this;
        }

        public CreateBillingPriceTransitionRequest build() {

            return new CreateBillingPriceTransitionRequest(
                subscriptionItemId, priceTransitionRequest);
        }

    }
}
