/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;


import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

/**
 * CreateInvitationPublicMetadata - Metadata that will be attached to the newly created invitation.
 * The value of this property should be a well-formed JSON object.
 * Once the user accepts the invitation and signs up, these metadata will end up in the user's public metadata.
 */

public class CreateInvitationPublicMetadata {

    @JsonCreator
    public CreateInvitationPublicMetadata() {
        
        
    }

    public final static Builder builder() {
        return new Builder();
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        return true;
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            );
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateInvitationPublicMetadata.class);
    }
    
    public final static class Builder {  
        
        private Builder() {
          // force use of static builder() method
        }
        
        public CreateInvitationPublicMetadata build() {
            return new CreateInvitationPublicMetadata(
                );
        }
    }
}

