/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import java.lang.String;

public class DeleteEmailAddressRequestBuilder {

    private String emailAddressId;
    private final SDKMethodInterfaces.MethodCallDeleteEmailAddress sdk;

    public DeleteEmailAddressRequestBuilder(SDKMethodInterfaces.MethodCallDeleteEmailAddress sdk) {
        this.sdk = sdk;
    }

    public DeleteEmailAddressRequestBuilder emailAddressId(String emailAddressId) {
        Utils.checkNotNull(emailAddressId, "emailAddressId");
        this.emailAddressId = emailAddressId;
        return this;
    }

    public DeleteEmailAddressResponse call() throws Exception {

        return sdk.delete(
            emailAddressId);
    }
}
