/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import static com.clerk.backend_api.operations.Operations.RequestOperation;

import com.clerk.backend_api.SDKConfiguration;
import com.clerk.backend_api.operations.DeleteBlocklistIdentifier;
import com.clerk.backend_api.utils.Headers;
import com.clerk.backend_api.utils.Options;
import com.clerk.backend_api.utils.RetryConfig;
import com.clerk.backend_api.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class DeleteBlocklistIdentifierRequestBuilder {

    private String identifierId;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public DeleteBlocklistIdentifierRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteBlocklistIdentifierRequestBuilder identifierId(String identifierId) {
        Utils.checkNotNull(identifierId, "identifierId");
        this.identifierId = identifierId;
        return this;
    }
                
    public DeleteBlocklistIdentifierRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public DeleteBlocklistIdentifierRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }


    private DeleteBlocklistIdentifierRequest buildRequest() {

        DeleteBlocklistIdentifierRequest request = new DeleteBlocklistIdentifierRequest(identifierId);

        return request;
    }

    public DeleteBlocklistIdentifierResponse call() {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        RequestOperation<DeleteBlocklistIdentifierRequest, DeleteBlocklistIdentifierResponse> operation
              = new DeleteBlocklistIdentifier.Sync(sdkConfiguration, options, _headers);
        DeleteBlocklistIdentifierRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
