/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;

/**
 * DeleteApiKeyResponseBody
 * 
 * <p>200 OK
 */
public class DeleteApiKeyResponseBody {

    @JsonProperty("id")
    private String id;


    @JsonProperty("object")
    private DeleteApiKeyObject object;


    @JsonProperty("deleted")
    private boolean deleted;

    @JsonCreator
    public DeleteApiKeyResponseBody(
            @JsonProperty("id") String id,
            @JsonProperty("object") DeleteApiKeyObject object,
            @JsonProperty("deleted") boolean deleted) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(object, "object");
        Utils.checkNotNull(deleted, "deleted");
        this.id = id;
        this.object = object;
        this.deleted = deleted;
    }

    @JsonIgnore
    public String id() {
        return id;
    }

    @JsonIgnore
    public DeleteApiKeyObject object() {
        return object;
    }

    @JsonIgnore
    public boolean deleted() {
        return deleted;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DeleteApiKeyResponseBody withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public DeleteApiKeyResponseBody withObject(DeleteApiKeyObject object) {
        Utils.checkNotNull(object, "object");
        this.object = object;
        return this;
    }

    public DeleteApiKeyResponseBody withDeleted(boolean deleted) {
        Utils.checkNotNull(deleted, "deleted");
        this.deleted = deleted;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteApiKeyResponseBody other = (DeleteApiKeyResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.deleted, other.deleted);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, object, deleted);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteApiKeyResponseBody.class,
                "id", id,
                "object", object,
                "deleted", deleted);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private DeleteApiKeyObject object;

        private Boolean deleted;

        private Builder() {
          // force use of static builder() method
        }


        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        public Builder object(DeleteApiKeyObject object) {
            Utils.checkNotNull(object, "object");
            this.object = object;
            return this;
        }


        public Builder deleted(boolean deleted) {
            Utils.checkNotNull(deleted, "deleted");
            this.deleted = deleted;
            return this;
        }

        public DeleteApiKeyResponseBody build() {

            return new DeleteApiKeyResponseBody(
                id, object, deleted);
        }

    }
}
