/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import static com.clerk.backend_api.operations.Operations.RequestOperation;

import com.clerk.backend_api.SDKConfiguration;
import com.clerk.backend_api.operations.DeleteApiKey;
import com.clerk.backend_api.utils.Headers;
import com.clerk.backend_api.utils.Options;
import com.clerk.backend_api.utils.RetryConfig;
import com.clerk.backend_api.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class DeleteApiKeyRequestBuilder {

    private String apiKeyID;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public DeleteApiKeyRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteApiKeyRequestBuilder apiKeyID(String apiKeyID) {
        Utils.checkNotNull(apiKeyID, "apiKeyID");
        this.apiKeyID = apiKeyID;
        return this;
    }
                
    public DeleteApiKeyRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public DeleteApiKeyRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }


    private DeleteApiKeyRequest buildRequest() {

        DeleteApiKeyRequest request = new DeleteApiKeyRequest(apiKeyID);

        return request;
    }

    public DeleteApiKeyResponse call() {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        RequestOperation<DeleteApiKeyRequest, DeleteApiKeyResponse> operation
              = new DeleteApiKey.Sync(sdkConfiguration, options, _headers);
        DeleteApiKeyRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
