/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.models.components.PaginatedBillingPaymentAttemptResponse;
import com.clerk.backend_api.utils.Response;
import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class GetBillingStatementPaymentAttemptsResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * A list of billing payment attempts.
     */
    private Optional<? extends PaginatedBillingPaymentAttemptResponse> paginatedBillingPaymentAttemptResponse;

    @JsonCreator
    public GetBillingStatementPaymentAttemptsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends PaginatedBillingPaymentAttemptResponse> paginatedBillingPaymentAttemptResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(paginatedBillingPaymentAttemptResponse, "paginatedBillingPaymentAttemptResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.paginatedBillingPaymentAttemptResponse = paginatedBillingPaymentAttemptResponse;
    }
    
    public GetBillingStatementPaymentAttemptsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * A list of billing payment attempts.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaginatedBillingPaymentAttemptResponse> paginatedBillingPaymentAttemptResponse() {
        return (Optional<PaginatedBillingPaymentAttemptResponse>) paginatedBillingPaymentAttemptResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetBillingStatementPaymentAttemptsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetBillingStatementPaymentAttemptsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetBillingStatementPaymentAttemptsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * A list of billing payment attempts.
     */
    public GetBillingStatementPaymentAttemptsResponse withPaginatedBillingPaymentAttemptResponse(PaginatedBillingPaymentAttemptResponse paginatedBillingPaymentAttemptResponse) {
        Utils.checkNotNull(paginatedBillingPaymentAttemptResponse, "paginatedBillingPaymentAttemptResponse");
        this.paginatedBillingPaymentAttemptResponse = Optional.ofNullable(paginatedBillingPaymentAttemptResponse);
        return this;
    }


    /**
     * A list of billing payment attempts.
     */
    public GetBillingStatementPaymentAttemptsResponse withPaginatedBillingPaymentAttemptResponse(Optional<? extends PaginatedBillingPaymentAttemptResponse> paginatedBillingPaymentAttemptResponse) {
        Utils.checkNotNull(paginatedBillingPaymentAttemptResponse, "paginatedBillingPaymentAttemptResponse");
        this.paginatedBillingPaymentAttemptResponse = paginatedBillingPaymentAttemptResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetBillingStatementPaymentAttemptsResponse other = (GetBillingStatementPaymentAttemptsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.paginatedBillingPaymentAttemptResponse, other.paginatedBillingPaymentAttemptResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            paginatedBillingPaymentAttemptResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetBillingStatementPaymentAttemptsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "paginatedBillingPaymentAttemptResponse", paginatedBillingPaymentAttemptResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Optional<? extends PaginatedBillingPaymentAttemptResponse> paginatedBillingPaymentAttemptResponse = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * A list of billing payment attempts.
         */
        public Builder paginatedBillingPaymentAttemptResponse(PaginatedBillingPaymentAttemptResponse paginatedBillingPaymentAttemptResponse) {
            Utils.checkNotNull(paginatedBillingPaymentAttemptResponse, "paginatedBillingPaymentAttemptResponse");
            this.paginatedBillingPaymentAttemptResponse = Optional.ofNullable(paginatedBillingPaymentAttemptResponse);
            return this;
        }

        /**
         * A list of billing payment attempts.
         */
        public Builder paginatedBillingPaymentAttemptResponse(Optional<? extends PaginatedBillingPaymentAttemptResponse> paginatedBillingPaymentAttemptResponse) {
            Utils.checkNotNull(paginatedBillingPaymentAttemptResponse, "paginatedBillingPaymentAttemptResponse");
            this.paginatedBillingPaymentAttemptResponse = paginatedBillingPaymentAttemptResponse;
            return this;
        }

        public GetBillingStatementPaymentAttemptsResponse build() {

            return new GetBillingStatementPaymentAttemptsResponse(
                contentType, statusCode, rawResponse,
                paginatedBillingPaymentAttemptResponse);
        }

    }
}
