/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.SpeakeasyMetadata;
import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;


public class GetOrganizationPermissionRequest {
    /**
     * The ID of the permission to retrieve
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=permission_id")
    private String permissionId;

    @JsonCreator
    public GetOrganizationPermissionRequest(
            String permissionId) {
        Utils.checkNotNull(permissionId, "permissionId");
        this.permissionId = permissionId;
    }

    /**
     * The ID of the permission to retrieve
     */
    @JsonIgnore
    public String permissionId() {
        return permissionId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the permission to retrieve
     */
    public GetOrganizationPermissionRequest withPermissionId(String permissionId) {
        Utils.checkNotNull(permissionId, "permissionId");
        this.permissionId = permissionId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetOrganizationPermissionRequest other = (GetOrganizationPermissionRequest) o;
        return 
            Utils.enhancedDeepEquals(this.permissionId, other.permissionId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            permissionId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetOrganizationPermissionRequest.class,
                "permissionId", permissionId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String permissionId;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The ID of the permission to retrieve
         */
        public Builder permissionId(String permissionId) {
            Utils.checkNotNull(permissionId, "permissionId");
            this.permissionId = permissionId;
            return this;
        }

        public GetOrganizationPermissionRequest build() {

            return new GetOrganizationPermissionRequest(
                permissionId);
        }

    }
}
