/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import static com.clerk.backend_api.operations.Operations.RequestOperation;

import com.clerk.backend_api.SDKConfiguration;
import com.clerk.backend_api.operations.GetSCIMDirectory;
import com.clerk.backend_api.utils.Headers;
import com.clerk.backend_api.utils.Options;
import com.clerk.backend_api.utils.RetryConfig;
import com.clerk.backend_api.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetSCIMDirectoryRequestBuilder {

    private String scimDirectoryId;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetSCIMDirectoryRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetSCIMDirectoryRequestBuilder scimDirectoryId(String scimDirectoryId) {
        Utils.checkNotNull(scimDirectoryId, "scimDirectoryId");
        this.scimDirectoryId = scimDirectoryId;
        return this;
    }
                
    public GetSCIMDirectoryRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public GetSCIMDirectoryRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }


    private GetSCIMDirectoryRequest buildRequest() {

        GetSCIMDirectoryRequest request = new GetSCIMDirectoryRequest(scimDirectoryId);

        return request;
    }

    public GetSCIMDirectoryResponse call() {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        RequestOperation<GetSCIMDirectoryRequest, GetSCIMDirectoryResponse> operation
              = new GetSCIMDirectory.Sync(sdkConfiguration, options, _headers);
        GetSCIMDirectoryRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
