/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.util.Optional;

public class ListRedirectURLsResponse implements com.clerk.backend_api.utils.Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * List of Redirect URLs
     */
    private Optional<? extends java.util.List<com.clerk.backend_api.models.components.RedirectURL>> redirectURLList;

    @JsonCreator
    public ListRedirectURLsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends java.util.List<com.clerk.backend_api.models.components.RedirectURL>> redirectURLList) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(redirectURLList, "redirectURLList");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.redirectURLList = redirectURLList;
    }
    
    public ListRedirectURLsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * List of Redirect URLs
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<java.util.List<com.clerk.backend_api.models.components.RedirectURL>> redirectURLList() {
        return (Optional<java.util.List<com.clerk.backend_api.models.components.RedirectURL>>) redirectURLList;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public ListRedirectURLsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ListRedirectURLsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListRedirectURLsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * List of Redirect URLs
     */
    public ListRedirectURLsResponse withRedirectURLList(java.util.List<com.clerk.backend_api.models.components.RedirectURL> redirectURLList) {
        Utils.checkNotNull(redirectURLList, "redirectURLList");
        this.redirectURLList = Optional.ofNullable(redirectURLList);
        return this;
    }

    /**
     * List of Redirect URLs
     */
    public ListRedirectURLsResponse withRedirectURLList(Optional<? extends java.util.List<com.clerk.backend_api.models.components.RedirectURL>> redirectURLList) {
        Utils.checkNotNull(redirectURLList, "redirectURLList");
        this.redirectURLList = redirectURLList;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListRedirectURLsResponse other = (ListRedirectURLsResponse) o;
        return 
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            java.util.Objects.deepEquals(this.redirectURLList, other.redirectURLList);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            redirectURLList);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListRedirectURLsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "redirectURLList", redirectURLList);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends java.util.List<com.clerk.backend_api.models.components.RedirectURL>> redirectURLList = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * List of Redirect URLs
         */
        public Builder redirectURLList(java.util.List<com.clerk.backend_api.models.components.RedirectURL> redirectURLList) {
            Utils.checkNotNull(redirectURLList, "redirectURLList");
            this.redirectURLList = Optional.ofNullable(redirectURLList);
            return this;
        }

        /**
         * List of Redirect URLs
         */
        public Builder redirectURLList(Optional<? extends java.util.List<com.clerk.backend_api.models.components.RedirectURL>> redirectURLList) {
            Utils.checkNotNull(redirectURLList, "redirectURLList");
            this.redirectURLList = redirectURLList;
            return this;
        }
        
        public ListRedirectURLsResponse build() {
            return new ListRedirectURLsResponse(
                contentType,
                statusCode,
                rawResponse,
                redirectURLList);
        }
    }
}

