/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.LazySingletonValue;
import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class ReplaceUserPhoneNumberRequestBody {
    /**
     * The new phone number. Must adhere to the E.164 standard for phone number format.
     */
    @JsonProperty("phone_number")
    private String phoneNumber;

    /**
     * Controls the status of the replacement phone number. Defaults to `verified`. Set to
     * `reserved` to create it reserved (unverified but usable for sign-in and locked)
     * instead of verified.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identification_status")
    private Optional<? extends ReplaceUserPhoneNumberIdentificationStatus> identificationStatus;

    @JsonCreator
    public ReplaceUserPhoneNumberRequestBody(
            @JsonProperty("phone_number") String phoneNumber,
            @JsonProperty("identification_status") Optional<? extends ReplaceUserPhoneNumberIdentificationStatus> identificationStatus) {
        Utils.checkNotNull(phoneNumber, "phoneNumber");
        Utils.checkNotNull(identificationStatus, "identificationStatus");
        this.phoneNumber = phoneNumber;
        this.identificationStatus = identificationStatus;
    }
    
    public ReplaceUserPhoneNumberRequestBody(
            String phoneNumber) {
        this(phoneNumber, Optional.empty());
    }

    /**
     * The new phone number. Must adhere to the E.164 standard for phone number format.
     */
    @JsonIgnore
    public String phoneNumber() {
        return phoneNumber;
    }

    /**
     * Controls the status of the replacement phone number. Defaults to `verified`. Set to
     * `reserved` to create it reserved (unverified but usable for sign-in and locked)
     * instead of verified.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ReplaceUserPhoneNumberIdentificationStatus> identificationStatus() {
        return (Optional<ReplaceUserPhoneNumberIdentificationStatus>) identificationStatus;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The new phone number. Must adhere to the E.164 standard for phone number format.
     */
    public ReplaceUserPhoneNumberRequestBody withPhoneNumber(String phoneNumber) {
        Utils.checkNotNull(phoneNumber, "phoneNumber");
        this.phoneNumber = phoneNumber;
        return this;
    }

    /**
     * Controls the status of the replacement phone number. Defaults to `verified`. Set to
     * `reserved` to create it reserved (unverified but usable for sign-in and locked)
     * instead of verified.
     */
    public ReplaceUserPhoneNumberRequestBody withIdentificationStatus(ReplaceUserPhoneNumberIdentificationStatus identificationStatus) {
        Utils.checkNotNull(identificationStatus, "identificationStatus");
        this.identificationStatus = Optional.ofNullable(identificationStatus);
        return this;
    }


    /**
     * Controls the status of the replacement phone number. Defaults to `verified`. Set to
     * `reserved` to create it reserved (unverified but usable for sign-in and locked)
     * instead of verified.
     */
    public ReplaceUserPhoneNumberRequestBody withIdentificationStatus(Optional<? extends ReplaceUserPhoneNumberIdentificationStatus> identificationStatus) {
        Utils.checkNotNull(identificationStatus, "identificationStatus");
        this.identificationStatus = identificationStatus;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReplaceUserPhoneNumberRequestBody other = (ReplaceUserPhoneNumberRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.phoneNumber, other.phoneNumber) &&
            Utils.enhancedDeepEquals(this.identificationStatus, other.identificationStatus);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            phoneNumber, identificationStatus);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ReplaceUserPhoneNumberRequestBody.class,
                "phoneNumber", phoneNumber,
                "identificationStatus", identificationStatus);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String phoneNumber;

        private Optional<? extends ReplaceUserPhoneNumberIdentificationStatus> identificationStatus;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The new phone number. Must adhere to the E.164 standard for phone number format.
         */
        public Builder phoneNumber(String phoneNumber) {
            Utils.checkNotNull(phoneNumber, "phoneNumber");
            this.phoneNumber = phoneNumber;
            return this;
        }


        /**
         * Controls the status of the replacement phone number. Defaults to `verified`. Set to
         * `reserved` to create it reserved (unverified but usable for sign-in and locked)
         * instead of verified.
         */
        public Builder identificationStatus(ReplaceUserPhoneNumberIdentificationStatus identificationStatus) {
            Utils.checkNotNull(identificationStatus, "identificationStatus");
            this.identificationStatus = Optional.ofNullable(identificationStatus);
            return this;
        }

        /**
         * Controls the status of the replacement phone number. Defaults to `verified`. Set to
         * `reserved` to create it reserved (unverified but usable for sign-in and locked)
         * instead of verified.
         */
        public Builder identificationStatus(Optional<? extends ReplaceUserPhoneNumberIdentificationStatus> identificationStatus) {
            Utils.checkNotNull(identificationStatus, "identificationStatus");
            this.identificationStatus = identificationStatus;
            return this;
        }

        public ReplaceUserPhoneNumberRequestBody build() {
            if (identificationStatus == null) {
                identificationStatus = _SINGLETON_VALUE_IdentificationStatus.value();
            }

            return new ReplaceUserPhoneNumberRequestBody(
                phoneNumber, identificationStatus);
        }


        private static final LazySingletonValue<Optional<? extends ReplaceUserPhoneNumberIdentificationStatus>> _SINGLETON_VALUE_IdentificationStatus =
                new LazySingletonValue<>(
                        "identification_status",
                        "\"verified\"",
                        new TypeReference<Optional<? extends ReplaceUserPhoneNumberIdentificationStatus>>() {});
    }
}
