/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.LazySingletonValue;
import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class ReplaceUserEmailAddressRequestBody {
    /**
     * The new email address. Must adhere to the RFC 5322 specification for email address format.
     */
    @JsonProperty("email_address")
    private String emailAddress;

    /**
     * Controls the status of the replacement email address. Defaults to `verified`. Set to
     * `reserved` to create it reserved (unverified but usable for sign-in and locked so no
     * other user can claim it), or to `unverified` to create it neither usable for sign-in
     * nor locked.
     * 
     * <p>**Warning:** `unverified` can lock the user out of their account. An unverified email
     * address cannot be used to sign in, so if the user has no other verified or reserved
     * identifier, they will be unable to authenticate and unable to verify this address.
     * Prefer `reserved` unless you specifically need the address left unclaimed — for
     * example so that another user can also hold it until one of them verifies it.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identification_status")
    private Optional<? extends IdentificationStatus> identificationStatus;

    /**
     * If set to `true`, the user's previous primary email address is notified that the
     * primary email address has changed. No notification is sent when the replacement
     * is the user's current primary email address. By default, no notification is sent.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notify_primary_email_address_changed")
    private JsonNullable<Boolean> notifyPrimaryEmailAddressChanged;

    @JsonCreator
    public ReplaceUserEmailAddressRequestBody(
            @JsonProperty("email_address") String emailAddress,
            @JsonProperty("identification_status") Optional<? extends IdentificationStatus> identificationStatus,
            @JsonProperty("notify_primary_email_address_changed") JsonNullable<Boolean> notifyPrimaryEmailAddressChanged) {
        Utils.checkNotNull(emailAddress, "emailAddress");
        Utils.checkNotNull(identificationStatus, "identificationStatus");
        Utils.checkNotNull(notifyPrimaryEmailAddressChanged, "notifyPrimaryEmailAddressChanged");
        this.emailAddress = emailAddress;
        this.identificationStatus = identificationStatus;
        this.notifyPrimaryEmailAddressChanged = notifyPrimaryEmailAddressChanged;
    }
    
    public ReplaceUserEmailAddressRequestBody(
            String emailAddress) {
        this(emailAddress, Optional.empty(), JsonNullable.undefined());
    }

    /**
     * The new email address. Must adhere to the RFC 5322 specification for email address format.
     */
    @JsonIgnore
    public String emailAddress() {
        return emailAddress;
    }

    /**
     * Controls the status of the replacement email address. Defaults to `verified`. Set to
     * `reserved` to create it reserved (unverified but usable for sign-in and locked so no
     * other user can claim it), or to `unverified` to create it neither usable for sign-in
     * nor locked.
     * 
     * <p>**Warning:** `unverified` can lock the user out of their account. An unverified email
     * address cannot be used to sign in, so if the user has no other verified or reserved
     * identifier, they will be unable to authenticate and unable to verify this address.
     * Prefer `reserved` unless you specifically need the address left unclaimed — for
     * example so that another user can also hold it until one of them verifies it.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<IdentificationStatus> identificationStatus() {
        return (Optional<IdentificationStatus>) identificationStatus;
    }

    /**
     * If set to `true`, the user's previous primary email address is notified that the
     * primary email address has changed. No notification is sent when the replacement
     * is the user's current primary email address. By default, no notification is sent.
     */
    @JsonIgnore
    public JsonNullable<Boolean> notifyPrimaryEmailAddressChanged() {
        return notifyPrimaryEmailAddressChanged;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The new email address. Must adhere to the RFC 5322 specification for email address format.
     */
    public ReplaceUserEmailAddressRequestBody withEmailAddress(String emailAddress) {
        Utils.checkNotNull(emailAddress, "emailAddress");
        this.emailAddress = emailAddress;
        return this;
    }

    /**
     * Controls the status of the replacement email address. Defaults to `verified`. Set to
     * `reserved` to create it reserved (unverified but usable for sign-in and locked so no
     * other user can claim it), or to `unverified` to create it neither usable for sign-in
     * nor locked.
     * 
     * <p>**Warning:** `unverified` can lock the user out of their account. An unverified email
     * address cannot be used to sign in, so if the user has no other verified or reserved
     * identifier, they will be unable to authenticate and unable to verify this address.
     * Prefer `reserved` unless you specifically need the address left unclaimed — for
     * example so that another user can also hold it until one of them verifies it.
     */
    public ReplaceUserEmailAddressRequestBody withIdentificationStatus(IdentificationStatus identificationStatus) {
        Utils.checkNotNull(identificationStatus, "identificationStatus");
        this.identificationStatus = Optional.ofNullable(identificationStatus);
        return this;
    }


    /**
     * Controls the status of the replacement email address. Defaults to `verified`. Set to
     * `reserved` to create it reserved (unverified but usable for sign-in and locked so no
     * other user can claim it), or to `unverified` to create it neither usable for sign-in
     * nor locked.
     * 
     * <p>**Warning:** `unverified` can lock the user out of their account. An unverified email
     * address cannot be used to sign in, so if the user has no other verified or reserved
     * identifier, they will be unable to authenticate and unable to verify this address.
     * Prefer `reserved` unless you specifically need the address left unclaimed — for
     * example so that another user can also hold it until one of them verifies it.
     */
    public ReplaceUserEmailAddressRequestBody withIdentificationStatus(Optional<? extends IdentificationStatus> identificationStatus) {
        Utils.checkNotNull(identificationStatus, "identificationStatus");
        this.identificationStatus = identificationStatus;
        return this;
    }

    /**
     * If set to `true`, the user's previous primary email address is notified that the
     * primary email address has changed. No notification is sent when the replacement
     * is the user's current primary email address. By default, no notification is sent.
     */
    public ReplaceUserEmailAddressRequestBody withNotifyPrimaryEmailAddressChanged(boolean notifyPrimaryEmailAddressChanged) {
        Utils.checkNotNull(notifyPrimaryEmailAddressChanged, "notifyPrimaryEmailAddressChanged");
        this.notifyPrimaryEmailAddressChanged = JsonNullable.of(notifyPrimaryEmailAddressChanged);
        return this;
    }

    /**
     * If set to `true`, the user's previous primary email address is notified that the
     * primary email address has changed. No notification is sent when the replacement
     * is the user's current primary email address. By default, no notification is sent.
     */
    public ReplaceUserEmailAddressRequestBody withNotifyPrimaryEmailAddressChanged(JsonNullable<Boolean> notifyPrimaryEmailAddressChanged) {
        Utils.checkNotNull(notifyPrimaryEmailAddressChanged, "notifyPrimaryEmailAddressChanged");
        this.notifyPrimaryEmailAddressChanged = notifyPrimaryEmailAddressChanged;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReplaceUserEmailAddressRequestBody other = (ReplaceUserEmailAddressRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.emailAddress, other.emailAddress) &&
            Utils.enhancedDeepEquals(this.identificationStatus, other.identificationStatus) &&
            Utils.enhancedDeepEquals(this.notifyPrimaryEmailAddressChanged, other.notifyPrimaryEmailAddressChanged);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            emailAddress, identificationStatus, notifyPrimaryEmailAddressChanged);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ReplaceUserEmailAddressRequestBody.class,
                "emailAddress", emailAddress,
                "identificationStatus", identificationStatus,
                "notifyPrimaryEmailAddressChanged", notifyPrimaryEmailAddressChanged);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String emailAddress;

        private Optional<? extends IdentificationStatus> identificationStatus;

        private JsonNullable<Boolean> notifyPrimaryEmailAddressChanged;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The new email address. Must adhere to the RFC 5322 specification for email address format.
         */
        public Builder emailAddress(String emailAddress) {
            Utils.checkNotNull(emailAddress, "emailAddress");
            this.emailAddress = emailAddress;
            return this;
        }


        /**
         * Controls the status of the replacement email address. Defaults to `verified`. Set to
         * `reserved` to create it reserved (unverified but usable for sign-in and locked so no
         * other user can claim it), or to `unverified` to create it neither usable for sign-in
         * nor locked.
         * 
         * <p>**Warning:** `unverified` can lock the user out of their account. An unverified email
         * address cannot be used to sign in, so if the user has no other verified or reserved
         * identifier, they will be unable to authenticate and unable to verify this address.
         * Prefer `reserved` unless you specifically need the address left unclaimed — for
         * example so that another user can also hold it until one of them verifies it.
         */
        public Builder identificationStatus(IdentificationStatus identificationStatus) {
            Utils.checkNotNull(identificationStatus, "identificationStatus");
            this.identificationStatus = Optional.ofNullable(identificationStatus);
            return this;
        }

        /**
         * Controls the status of the replacement email address. Defaults to `verified`. Set to
         * `reserved` to create it reserved (unverified but usable for sign-in and locked so no
         * other user can claim it), or to `unverified` to create it neither usable for sign-in
         * nor locked.
         * 
         * <p>**Warning:** `unverified` can lock the user out of their account. An unverified email
         * address cannot be used to sign in, so if the user has no other verified or reserved
         * identifier, they will be unable to authenticate and unable to verify this address.
         * Prefer `reserved` unless you specifically need the address left unclaimed — for
         * example so that another user can also hold it until one of them verifies it.
         */
        public Builder identificationStatus(Optional<? extends IdentificationStatus> identificationStatus) {
            Utils.checkNotNull(identificationStatus, "identificationStatus");
            this.identificationStatus = identificationStatus;
            return this;
        }


        /**
         * If set to `true`, the user's previous primary email address is notified that the
         * primary email address has changed. No notification is sent when the replacement
         * is the user's current primary email address. By default, no notification is sent.
         */
        public Builder notifyPrimaryEmailAddressChanged(boolean notifyPrimaryEmailAddressChanged) {
            Utils.checkNotNull(notifyPrimaryEmailAddressChanged, "notifyPrimaryEmailAddressChanged");
            this.notifyPrimaryEmailAddressChanged = JsonNullable.of(notifyPrimaryEmailAddressChanged);
            return this;
        }

        /**
         * If set to `true`, the user's previous primary email address is notified that the
         * primary email address has changed. No notification is sent when the replacement
         * is the user's current primary email address. By default, no notification is sent.
         */
        public Builder notifyPrimaryEmailAddressChanged(JsonNullable<Boolean> notifyPrimaryEmailAddressChanged) {
            Utils.checkNotNull(notifyPrimaryEmailAddressChanged, "notifyPrimaryEmailAddressChanged");
            this.notifyPrimaryEmailAddressChanged = notifyPrimaryEmailAddressChanged;
            return this;
        }

        public ReplaceUserEmailAddressRequestBody build() {
            if (identificationStatus == null) {
                identificationStatus = _SINGLETON_VALUE_IdentificationStatus.value();
            }
            if (notifyPrimaryEmailAddressChanged == null) {
                notifyPrimaryEmailAddressChanged = _SINGLETON_VALUE_NotifyPrimaryEmailAddressChanged.value();
            }

            return new ReplaceUserEmailAddressRequestBody(
                emailAddress, identificationStatus, notifyPrimaryEmailAddressChanged);
        }


        private static final LazySingletonValue<Optional<? extends IdentificationStatus>> _SINGLETON_VALUE_IdentificationStatus =
                new LazySingletonValue<>(
                        "identification_status",
                        "\"verified\"",
                        new TypeReference<Optional<? extends IdentificationStatus>>() {});

        private static final LazySingletonValue<JsonNullable<Boolean>> _SINGLETON_VALUE_NotifyPrimaryEmailAddressChanged =
                new LazySingletonValue<>(
                        "notify_primary_email_address_changed",
                        "false",
                        new TypeReference<JsonNullable<Boolean>>() {});
    }
}
