/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import java.lang.String;

public class RevertTemplateRequestBuilder {

    private RevertTemplatePathParamTemplateType templateType;
    private String slug;
    private final SDKMethodInterfaces.MethodCallRevertTemplate sdk;

    public RevertTemplateRequestBuilder(SDKMethodInterfaces.MethodCallRevertTemplate sdk) {
        this.sdk = sdk;
    }

    public RevertTemplateRequestBuilder templateType(RevertTemplatePathParamTemplateType templateType) {
        Utils.checkNotNull(templateType, "templateType");
        this.templateType = templateType;
        return this;
    }

    public RevertTemplateRequestBuilder slug(String slug) {
        Utils.checkNotNull(slug, "slug");
        this.slug = slug;
        return this;
    }

    public RevertTemplateResponse call() throws Exception {

        return sdk.revert(
            templateType,
            slug);
    }
}
