/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum RevokeAdminPortalLinkTokenObject {
    ADMIN_PORTAL_LINK_TOKEN("admin_portal_link_token");

    @JsonValue
    private final String value;

    RevokeAdminPortalLinkTokenObject(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<RevokeAdminPortalLinkTokenObject> fromValue(String value) {
        for (RevokeAdminPortalLinkTokenObject o: RevokeAdminPortalLinkTokenObject.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

