/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import java.lang.String;

public class UnbanUserRequestBuilder {

    private String userId;
    private final SDKMethodInterfaces.MethodCallUnbanUser sdk;

    public UnbanUserRequestBuilder(SDKMethodInterfaces.MethodCallUnbanUser sdk) {
        this.sdk = sdk;
    }

    public UnbanUserRequestBuilder userId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }

    public UnbanUserResponse call() throws Exception {

        return sdk.unban(
            userId);
    }
}
