/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import java.util.Optional;

public class UpdateInstanceRestrictionsRequestBuilder {

    private Optional<? extends UpdateInstanceRestrictionsRequestBody> request = Optional.empty();
    private final SDKMethodInterfaces.MethodCallUpdateInstanceRestrictions sdk;

    public UpdateInstanceRestrictionsRequestBuilder(SDKMethodInterfaces.MethodCallUpdateInstanceRestrictions sdk) {
        this.sdk = sdk;
    }
                
    public UpdateInstanceRestrictionsRequestBuilder request(UpdateInstanceRestrictionsRequestBody request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public UpdateInstanceRestrictionsRequestBuilder request(Optional<? extends UpdateInstanceRestrictionsRequestBody> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public UpdateInstanceRestrictionsResponse call() throws Exception {

        return sdk.updateRestrictions(
            request);
    }
}
