/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;


import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;


public class UpdateDomainRequestBody {

    /**
     * The new domain name. For development instances, can contain the port,
     * i.e `myhostname:3000`. For production instances, must be a valid FQDN,
     * i.e `mysite.com`. Cannot contain protocol scheme.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private JsonNullable<String> name;

    /**
     * The full URL of the proxy that will forward requests to Clerk's Frontend API.
     * Can only be updated for production instances.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("proxy_url")
    private JsonNullable<String> proxyUrl;

    /**
     * Whether this is a domain for a secondary app, meaning that any subdomain provided is significant and
     * will be stored as part of the domain. This is useful for supporting multiple apps (one primary and
     * multiple secondaries) on the same root domain (eTLD+1).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_secondary")
    private JsonNullable<Boolean> isSecondary;

    @JsonCreator
    public UpdateDomainRequestBody(
            @JsonProperty("name") JsonNullable<String> name,
            @JsonProperty("proxy_url") JsonNullable<String> proxyUrl,
            @JsonProperty("is_secondary") JsonNullable<Boolean> isSecondary) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(proxyUrl, "proxyUrl");
        Utils.checkNotNull(isSecondary, "isSecondary");
        this.name = name;
        this.proxyUrl = proxyUrl;
        this.isSecondary = isSecondary;
    }
    
    public UpdateDomainRequestBody() {
        this(JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined());
    }

    /**
     * The new domain name. For development instances, can contain the port,
     * i.e `myhostname:3000`. For production instances, must be a valid FQDN,
     * i.e `mysite.com`. Cannot contain protocol scheme.
     */
    @JsonIgnore
    public JsonNullable<String> name() {
        return name;
    }

    /**
     * The full URL of the proxy that will forward requests to Clerk's Frontend API.
     * Can only be updated for production instances.
     */
    @JsonIgnore
    public JsonNullable<String> proxyUrl() {
        return proxyUrl;
    }

    /**
     * Whether this is a domain for a secondary app, meaning that any subdomain provided is significant and
     * will be stored as part of the domain. This is useful for supporting multiple apps (one primary and
     * multiple secondaries) on the same root domain (eTLD+1).
     */
    @JsonIgnore
    public JsonNullable<Boolean> isSecondary() {
        return isSecondary;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The new domain name. For development instances, can contain the port,
     * i.e `myhostname:3000`. For production instances, must be a valid FQDN,
     * i.e `mysite.com`. Cannot contain protocol scheme.
     */
    public UpdateDomainRequestBody withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = JsonNullable.of(name);
        return this;
    }

    /**
     * The new domain name. For development instances, can contain the port,
     * i.e `myhostname:3000`. For production instances, must be a valid FQDN,
     * i.e `mysite.com`. Cannot contain protocol scheme.
     */
    public UpdateDomainRequestBody withName(JsonNullable<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * The full URL of the proxy that will forward requests to Clerk's Frontend API.
     * Can only be updated for production instances.
     */
    public UpdateDomainRequestBody withProxyUrl(String proxyUrl) {
        Utils.checkNotNull(proxyUrl, "proxyUrl");
        this.proxyUrl = JsonNullable.of(proxyUrl);
        return this;
    }

    /**
     * The full URL of the proxy that will forward requests to Clerk's Frontend API.
     * Can only be updated for production instances.
     */
    public UpdateDomainRequestBody withProxyUrl(JsonNullable<String> proxyUrl) {
        Utils.checkNotNull(proxyUrl, "proxyUrl");
        this.proxyUrl = proxyUrl;
        return this;
    }

    /**
     * Whether this is a domain for a secondary app, meaning that any subdomain provided is significant and
     * will be stored as part of the domain. This is useful for supporting multiple apps (one primary and
     * multiple secondaries) on the same root domain (eTLD+1).
     */
    public UpdateDomainRequestBody withIsSecondary(boolean isSecondary) {
        Utils.checkNotNull(isSecondary, "isSecondary");
        this.isSecondary = JsonNullable.of(isSecondary);
        return this;
    }

    /**
     * Whether this is a domain for a secondary app, meaning that any subdomain provided is significant and
     * will be stored as part of the domain. This is useful for supporting multiple apps (one primary and
     * multiple secondaries) on the same root domain (eTLD+1).
     */
    public UpdateDomainRequestBody withIsSecondary(JsonNullable<Boolean> isSecondary) {
        Utils.checkNotNull(isSecondary, "isSecondary");
        this.isSecondary = isSecondary;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateDomainRequestBody other = (UpdateDomainRequestBody) o;
        return 
            Objects.deepEquals(this.name, other.name) &&
            Objects.deepEquals(this.proxyUrl, other.proxyUrl) &&
            Objects.deepEquals(this.isSecondary, other.isSecondary);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            name,
            proxyUrl,
            isSecondary);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateDomainRequestBody.class,
                "name", name,
                "proxyUrl", proxyUrl,
                "isSecondary", isSecondary);
    }
    
    public final static class Builder {
 
        private JsonNullable<String> name = JsonNullable.undefined();
 
        private JsonNullable<String> proxyUrl = JsonNullable.undefined();
 
        private JsonNullable<Boolean> isSecondary = JsonNullable.undefined();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The new domain name. For development instances, can contain the port,
         * i.e `myhostname:3000`. For production instances, must be a valid FQDN,
         * i.e `mysite.com`. Cannot contain protocol scheme.
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = JsonNullable.of(name);
            return this;
        }

        /**
         * The new domain name. For development instances, can contain the port,
         * i.e `myhostname:3000`. For production instances, must be a valid FQDN,
         * i.e `mysite.com`. Cannot contain protocol scheme.
         */
        public Builder name(JsonNullable<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        /**
         * The full URL of the proxy that will forward requests to Clerk's Frontend API.
         * Can only be updated for production instances.
         */
        public Builder proxyUrl(String proxyUrl) {
            Utils.checkNotNull(proxyUrl, "proxyUrl");
            this.proxyUrl = JsonNullable.of(proxyUrl);
            return this;
        }

        /**
         * The full URL of the proxy that will forward requests to Clerk's Frontend API.
         * Can only be updated for production instances.
         */
        public Builder proxyUrl(JsonNullable<String> proxyUrl) {
            Utils.checkNotNull(proxyUrl, "proxyUrl");
            this.proxyUrl = proxyUrl;
            return this;
        }

        /**
         * Whether this is a domain for a secondary app, meaning that any subdomain provided is significant and
         * will be stored as part of the domain. This is useful for supporting multiple apps (one primary and
         * multiple secondaries) on the same root domain (eTLD+1).
         */
        public Builder isSecondary(boolean isSecondary) {
            Utils.checkNotNull(isSecondary, "isSecondary");
            this.isSecondary = JsonNullable.of(isSecondary);
            return this;
        }

        /**
         * Whether this is a domain for a secondary app, meaning that any subdomain provided is significant and
         * will be stored as part of the domain. This is useful for supporting multiple apps (one primary and
         * multiple secondaries) on the same root domain (eTLD+1).
         */
        public Builder isSecondary(JsonNullable<Boolean> isSecondary) {
            Utils.checkNotNull(isSecondary, "isSecondary");
            this.isSecondary = isSecondary;
            return this;
        }
        
        public UpdateDomainRequestBody build() {
            return new UpdateDomainRequestBody(
                name,
                proxyUrl,
                isSecondary);
        }
    }
}

