/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * UpdateApiKeyResponseBody
 * 
 * <p>200 OK
 */
public class UpdateApiKeyResponseBody {

    @JsonProperty("object")
    private UpdateApiKeyObject object;


    @JsonProperty("id")
    private String id;


    @JsonProperty("type")
    private String type;


    @JsonProperty("subject")
    private String subject;


    @JsonProperty("name")
    private String name;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private JsonNullable<String> description;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("claims")
    private Optional<? extends Object> claims;


    @JsonProperty("scopes")
    private List<String> scopes;


    @JsonProperty("revoked")
    private boolean revoked;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("revocation_reason")
    private Optional<String> revocationReason;


    @JsonProperty("expired")
    private boolean expired;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("expiration")
    private Optional<Double> expiration;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("created_by")
    private Optional<String> createdBy;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("last_used_at")
    private Optional<Double> lastUsedAt;


    @JsonProperty("created_at")
    private double createdAt;


    @JsonProperty("updated_at")
    private double updatedAt;

    @JsonCreator
    public UpdateApiKeyResponseBody(
            @JsonProperty("object") UpdateApiKeyObject object,
            @JsonProperty("id") String id,
            @JsonProperty("type") String type,
            @JsonProperty("subject") String subject,
            @JsonProperty("name") String name,
            @JsonProperty("description") JsonNullable<String> description,
            @JsonProperty("claims") Optional<? extends Object> claims,
            @JsonProperty("scopes") List<String> scopes,
            @JsonProperty("revoked") boolean revoked,
            @JsonProperty("revocation_reason") Optional<String> revocationReason,
            @JsonProperty("expired") boolean expired,
            @JsonProperty("expiration") Optional<Double> expiration,
            @JsonProperty("created_by") Optional<String> createdBy,
            @JsonProperty("last_used_at") Optional<Double> lastUsedAt,
            @JsonProperty("created_at") double createdAt,
            @JsonProperty("updated_at") double updatedAt) {
        Utils.checkNotNull(object, "object");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(subject, "subject");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(claims, "claims");
        Utils.checkNotNull(scopes, "scopes");
        Utils.checkNotNull(revoked, "revoked");
        Utils.checkNotNull(revocationReason, "revocationReason");
        Utils.checkNotNull(expired, "expired");
        Utils.checkNotNull(expiration, "expiration");
        Utils.checkNotNull(createdBy, "createdBy");
        Utils.checkNotNull(lastUsedAt, "lastUsedAt");
        Utils.checkNotNull(createdAt, "createdAt");
        Utils.checkNotNull(updatedAt, "updatedAt");
        this.object = object;
        this.id = id;
        this.type = type;
        this.subject = subject;
        this.name = name;
        this.description = description;
        this.claims = claims;
        this.scopes = scopes;
        this.revoked = revoked;
        this.revocationReason = revocationReason;
        this.expired = expired;
        this.expiration = expiration;
        this.createdBy = createdBy;
        this.lastUsedAt = lastUsedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    
    public UpdateApiKeyResponseBody(
            UpdateApiKeyObject object,
            String id,
            String type,
            String subject,
            String name,
            List<String> scopes,
            boolean revoked,
            boolean expired,
            double createdAt,
            double updatedAt) {
        this(object, id, type,
            subject, name, JsonNullable.undefined(),
            Optional.empty(), scopes, revoked,
            Optional.empty(), expired, Optional.empty(),
            Optional.empty(), Optional.empty(), createdAt,
            updatedAt);
    }

    @JsonIgnore
    public UpdateApiKeyObject object() {
        return object;
    }

    @JsonIgnore
    public String id() {
        return id;
    }

    @JsonIgnore
    public String type() {
        return type;
    }

    @JsonIgnore
    public String subject() {
        return subject;
    }

    @JsonIgnore
    public String name() {
        return name;
    }

    @JsonIgnore
    public JsonNullable<String> description() {
        return description;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Object> claims() {
        return (Optional<Object>) claims;
    }

    @JsonIgnore
    public List<String> scopes() {
        return scopes;
    }

    @JsonIgnore
    public boolean revoked() {
        return revoked;
    }

    @JsonIgnore
    public Optional<String> revocationReason() {
        return revocationReason;
    }

    @JsonIgnore
    public boolean expired() {
        return expired;
    }

    @JsonIgnore
    public Optional<Double> expiration() {
        return expiration;
    }

    @JsonIgnore
    public Optional<String> createdBy() {
        return createdBy;
    }

    @JsonIgnore
    public Optional<Double> lastUsedAt() {
        return lastUsedAt;
    }

    @JsonIgnore
    public double createdAt() {
        return createdAt;
    }

    @JsonIgnore
    public double updatedAt() {
        return updatedAt;
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateApiKeyResponseBody withObject(UpdateApiKeyObject object) {
        Utils.checkNotNull(object, "object");
        this.object = object;
        return this;
    }

    public UpdateApiKeyResponseBody withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public UpdateApiKeyResponseBody withType(String type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    public UpdateApiKeyResponseBody withSubject(String subject) {
        Utils.checkNotNull(subject, "subject");
        this.subject = subject;
        return this;
    }

    public UpdateApiKeyResponseBody withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    public UpdateApiKeyResponseBody withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = JsonNullable.of(description);
        return this;
    }

    public UpdateApiKeyResponseBody withDescription(JsonNullable<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    public UpdateApiKeyResponseBody withClaims(Object claims) {
        Utils.checkNotNull(claims, "claims");
        this.claims = Optional.ofNullable(claims);
        return this;
    }


    public UpdateApiKeyResponseBody withClaims(Optional<? extends Object> claims) {
        Utils.checkNotNull(claims, "claims");
        this.claims = claims;
        return this;
    }

    public UpdateApiKeyResponseBody withScopes(List<String> scopes) {
        Utils.checkNotNull(scopes, "scopes");
        this.scopes = scopes;
        return this;
    }

    public UpdateApiKeyResponseBody withRevoked(boolean revoked) {
        Utils.checkNotNull(revoked, "revoked");
        this.revoked = revoked;
        return this;
    }

    public UpdateApiKeyResponseBody withRevocationReason(String revocationReason) {
        Utils.checkNotNull(revocationReason, "revocationReason");
        this.revocationReason = Optional.ofNullable(revocationReason);
        return this;
    }


    public UpdateApiKeyResponseBody withRevocationReason(Optional<String> revocationReason) {
        Utils.checkNotNull(revocationReason, "revocationReason");
        this.revocationReason = revocationReason;
        return this;
    }

    public UpdateApiKeyResponseBody withExpired(boolean expired) {
        Utils.checkNotNull(expired, "expired");
        this.expired = expired;
        return this;
    }

    public UpdateApiKeyResponseBody withExpiration(double expiration) {
        Utils.checkNotNull(expiration, "expiration");
        this.expiration = Optional.ofNullable(expiration);
        return this;
    }


    public UpdateApiKeyResponseBody withExpiration(Optional<Double> expiration) {
        Utils.checkNotNull(expiration, "expiration");
        this.expiration = expiration;
        return this;
    }

    public UpdateApiKeyResponseBody withCreatedBy(String createdBy) {
        Utils.checkNotNull(createdBy, "createdBy");
        this.createdBy = Optional.ofNullable(createdBy);
        return this;
    }


    public UpdateApiKeyResponseBody withCreatedBy(Optional<String> createdBy) {
        Utils.checkNotNull(createdBy, "createdBy");
        this.createdBy = createdBy;
        return this;
    }

    public UpdateApiKeyResponseBody withLastUsedAt(double lastUsedAt) {
        Utils.checkNotNull(lastUsedAt, "lastUsedAt");
        this.lastUsedAt = Optional.ofNullable(lastUsedAt);
        return this;
    }


    public UpdateApiKeyResponseBody withLastUsedAt(Optional<Double> lastUsedAt) {
        Utils.checkNotNull(lastUsedAt, "lastUsedAt");
        this.lastUsedAt = lastUsedAt;
        return this;
    }

    public UpdateApiKeyResponseBody withCreatedAt(double createdAt) {
        Utils.checkNotNull(createdAt, "createdAt");
        this.createdAt = createdAt;
        return this;
    }

    public UpdateApiKeyResponseBody withUpdatedAt(double updatedAt) {
        Utils.checkNotNull(updatedAt, "updatedAt");
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateApiKeyResponseBody other = (UpdateApiKeyResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.subject, other.subject) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.claims, other.claims) &&
            Utils.enhancedDeepEquals(this.scopes, other.scopes) &&
            Utils.enhancedDeepEquals(this.revoked, other.revoked) &&
            Utils.enhancedDeepEquals(this.revocationReason, other.revocationReason) &&
            Utils.enhancedDeepEquals(this.expired, other.expired) &&
            Utils.enhancedDeepEquals(this.expiration, other.expiration) &&
            Utils.enhancedDeepEquals(this.createdBy, other.createdBy) &&
            Utils.enhancedDeepEquals(this.lastUsedAt, other.lastUsedAt) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.updatedAt, other.updatedAt);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            object, id, type,
            subject, name, description,
            claims, scopes, revoked,
            revocationReason, expired, expiration,
            createdBy, lastUsedAt, createdAt,
            updatedAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateApiKeyResponseBody.class,
                "object", object,
                "id", id,
                "type", type,
                "subject", subject,
                "name", name,
                "description", description,
                "claims", claims,
                "scopes", scopes,
                "revoked", revoked,
                "revocationReason", revocationReason,
                "expired", expired,
                "expiration", expiration,
                "createdBy", createdBy,
                "lastUsedAt", lastUsedAt,
                "createdAt", createdAt,
                "updatedAt", updatedAt);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private UpdateApiKeyObject object;

        private String id;

        private String type;

        private String subject;

        private String name;

        private JsonNullable<String> description = JsonNullable.undefined();

        private Optional<? extends Object> claims = Optional.empty();

        private List<String> scopes;

        private Boolean revoked;

        private Optional<String> revocationReason = Optional.empty();

        private Boolean expired;

        private Optional<Double> expiration = Optional.empty();

        private Optional<String> createdBy = Optional.empty();

        private Optional<Double> lastUsedAt = Optional.empty();

        private Double createdAt;

        private Double updatedAt;

        private Builder() {
          // force use of static builder() method
        }


        public Builder object(UpdateApiKeyObject object) {
            Utils.checkNotNull(object, "object");
            this.object = object;
            return this;
        }


        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        public Builder type(String type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }


        public Builder subject(String subject) {
            Utils.checkNotNull(subject, "subject");
            this.subject = subject;
            return this;
        }


        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = JsonNullable.of(description);
            return this;
        }

        public Builder description(JsonNullable<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }


        public Builder claims(Object claims) {
            Utils.checkNotNull(claims, "claims");
            this.claims = Optional.ofNullable(claims);
            return this;
        }

        public Builder claims(Optional<? extends Object> claims) {
            Utils.checkNotNull(claims, "claims");
            this.claims = claims;
            return this;
        }


        public Builder scopes(List<String> scopes) {
            Utils.checkNotNull(scopes, "scopes");
            this.scopes = scopes;
            return this;
        }


        public Builder revoked(boolean revoked) {
            Utils.checkNotNull(revoked, "revoked");
            this.revoked = revoked;
            return this;
        }


        public Builder revocationReason(String revocationReason) {
            Utils.checkNotNull(revocationReason, "revocationReason");
            this.revocationReason = Optional.ofNullable(revocationReason);
            return this;
        }

        public Builder revocationReason(Optional<String> revocationReason) {
            Utils.checkNotNull(revocationReason, "revocationReason");
            this.revocationReason = revocationReason;
            return this;
        }


        public Builder expired(boolean expired) {
            Utils.checkNotNull(expired, "expired");
            this.expired = expired;
            return this;
        }


        public Builder expiration(double expiration) {
            Utils.checkNotNull(expiration, "expiration");
            this.expiration = Optional.ofNullable(expiration);
            return this;
        }

        public Builder expiration(Optional<Double> expiration) {
            Utils.checkNotNull(expiration, "expiration");
            this.expiration = expiration;
            return this;
        }


        public Builder createdBy(String createdBy) {
            Utils.checkNotNull(createdBy, "createdBy");
            this.createdBy = Optional.ofNullable(createdBy);
            return this;
        }

        public Builder createdBy(Optional<String> createdBy) {
            Utils.checkNotNull(createdBy, "createdBy");
            this.createdBy = createdBy;
            return this;
        }


        public Builder lastUsedAt(double lastUsedAt) {
            Utils.checkNotNull(lastUsedAt, "lastUsedAt");
            this.lastUsedAt = Optional.ofNullable(lastUsedAt);
            return this;
        }

        public Builder lastUsedAt(Optional<Double> lastUsedAt) {
            Utils.checkNotNull(lastUsedAt, "lastUsedAt");
            this.lastUsedAt = lastUsedAt;
            return this;
        }


        public Builder createdAt(double createdAt) {
            Utils.checkNotNull(createdAt, "createdAt");
            this.createdAt = createdAt;
            return this;
        }


        public Builder updatedAt(double updatedAt) {
            Utils.checkNotNull(updatedAt, "updatedAt");
            this.updatedAt = updatedAt;
            return this;
        }

        public UpdateApiKeyResponseBody build() {

            return new UpdateApiKeyResponseBody(
                object, id, type,
                subject, name, description,
                claims, scopes, revoked,
                revocationReason, expired, expiration,
                createdBy, lastUsedAt, createdAt,
                updatedAt);
        }

    }
}
