/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.Utils;
import java.lang.String;

public class UpdateOAuthApplicationRequestBuilder {

    private String oauthApplicationId;
    private UpdateOAuthApplicationRequestBody requestBody;
    private final SDKMethodInterfaces.MethodCallUpdateOAuthApplication sdk;

    public UpdateOAuthApplicationRequestBuilder(SDKMethodInterfaces.MethodCallUpdateOAuthApplication sdk) {
        this.sdk = sdk;
    }

    public UpdateOAuthApplicationRequestBuilder oauthApplicationId(String oauthApplicationId) {
        Utils.checkNotNull(oauthApplicationId, "oauthApplicationId");
        this.oauthApplicationId = oauthApplicationId;
        return this;
    }

    public UpdateOAuthApplicationRequestBuilder requestBody(UpdateOAuthApplicationRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public UpdateOAuthApplicationResponse call() throws Exception {

        return sdk.update(
            oauthApplicationId,
            requestBody);
    }
}
