/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import static com.clerk.backend_api.operations.Operations.RequestOperation;

import com.clerk.backend_api.SDKConfiguration;
import com.clerk.backend_api.operations.UpdateInstanceOAuthApplicationSettings;
import com.clerk.backend_api.utils.Headers;
import com.clerk.backend_api.utils.Options;
import com.clerk.backend_api.utils.RetryConfig;
import com.clerk.backend_api.utils.Utils;
import java.util.Optional;

public class UpdateInstanceOAuthApplicationSettingsRequestBuilder {

    private Optional<? extends UpdateInstanceOAuthApplicationSettingsRequestBody> request = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public UpdateInstanceOAuthApplicationSettingsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public UpdateInstanceOAuthApplicationSettingsRequestBuilder request(UpdateInstanceOAuthApplicationSettingsRequestBody request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public UpdateInstanceOAuthApplicationSettingsRequestBuilder request(Optional<? extends UpdateInstanceOAuthApplicationSettingsRequestBody> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public UpdateInstanceOAuthApplicationSettingsRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public UpdateInstanceOAuthApplicationSettingsRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public UpdateInstanceOAuthApplicationSettingsResponse call() {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        RequestOperation<Optional<? extends UpdateInstanceOAuthApplicationSettingsRequestBody>, UpdateInstanceOAuthApplicationSettingsResponse> operation
              = new UpdateInstanceOAuthApplicationSettings.Sync(sdkConfiguration, options, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
