/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.clerk.backend_api.utils.SpeakeasyMetadata;
import com.clerk.backend_api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class UploadOAuthApplicationLogoRequest {
    /**
     * The ID of the OAuth application for which to upload a logo
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=oauth_application_id")
    private String oauthApplicationId;


    @SpeakeasyMetadata("request:mediaType=multipart/form-data")
    private Optional<? extends UploadOAuthApplicationLogoRequestBody> requestBody;

    @JsonCreator
    public UploadOAuthApplicationLogoRequest(
            String oauthApplicationId,
            Optional<? extends UploadOAuthApplicationLogoRequestBody> requestBody) {
        Utils.checkNotNull(oauthApplicationId, "oauthApplicationId");
        Utils.checkNotNull(requestBody, "requestBody");
        this.oauthApplicationId = oauthApplicationId;
        this.requestBody = requestBody;
    }
    
    public UploadOAuthApplicationLogoRequest(
            String oauthApplicationId) {
        this(oauthApplicationId, Optional.empty());
    }

    /**
     * The ID of the OAuth application for which to upload a logo
     */
    @JsonIgnore
    public String oauthApplicationId() {
        return oauthApplicationId;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<UploadOAuthApplicationLogoRequestBody> requestBody() {
        return (Optional<UploadOAuthApplicationLogoRequestBody>) requestBody;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the OAuth application for which to upload a logo
     */
    public UploadOAuthApplicationLogoRequest withOauthApplicationId(String oauthApplicationId) {
        Utils.checkNotNull(oauthApplicationId, "oauthApplicationId");
        this.oauthApplicationId = oauthApplicationId;
        return this;
    }

    public UploadOAuthApplicationLogoRequest withRequestBody(UploadOAuthApplicationLogoRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = Optional.ofNullable(requestBody);
        return this;
    }


    public UploadOAuthApplicationLogoRequest withRequestBody(Optional<? extends UploadOAuthApplicationLogoRequestBody> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UploadOAuthApplicationLogoRequest other = (UploadOAuthApplicationLogoRequest) o;
        return 
            Utils.enhancedDeepEquals(this.oauthApplicationId, other.oauthApplicationId) &&
            Utils.enhancedDeepEquals(this.requestBody, other.requestBody);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            oauthApplicationId, requestBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UploadOAuthApplicationLogoRequest.class,
                "oauthApplicationId", oauthApplicationId,
                "requestBody", requestBody);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String oauthApplicationId;

        private Optional<? extends UploadOAuthApplicationLogoRequestBody> requestBody = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The ID of the OAuth application for which to upload a logo
         */
        public Builder oauthApplicationId(String oauthApplicationId) {
            Utils.checkNotNull(oauthApplicationId, "oauthApplicationId");
            this.oauthApplicationId = oauthApplicationId;
            return this;
        }


        public Builder requestBody(UploadOAuthApplicationLogoRequestBody requestBody) {
            Utils.checkNotNull(requestBody, "requestBody");
            this.requestBody = Optional.ofNullable(requestBody);
            return this;
        }

        public Builder requestBody(Optional<? extends UploadOAuthApplicationLogoRequestBody> requestBody) {
            Utils.checkNotNull(requestBody, "requestBody");
            this.requestBody = requestBody;
            return this;
        }

        public UploadOAuthApplicationLogoRequest build() {

            return new UploadOAuthApplicationLogoRequest(
                oauthApplicationId, requestBody);
        }

    }
}
