/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.clerk.backend_api.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * Verified
 * 
 * <p>Filter by verification status
 */
public enum Verified {
    TRUE("true"),
    FALSE("false");

    @JsonValue
    private final String value;

    Verified(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Verified> fromValue(String value) {
        for (Verified o: Verified.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

